extends Node
## LocalizationManager.gd - small UI localization helper.
## Static gameplay data remains in its source JSON for this pass.

signal locale_changed(locale: String)

const DEFAULT_LOCALE := "en"
const LANGUAGES: Array[Dictionary] = [
	{"code": "en", "label": "English"},
	{"code": "tr", "label": "Türkçe"},
]

const TEXT := {
	"en": {
		"brand.subtitle": "SILENT CARTOGRAPHY",
		"common.back": "BACK",
		"common.begin": "BEGIN",
		"common.close": "CLOSE",
		"common.continue": "CONTINUE",
		"common.main_menu": "MAIN MENU",
		"common.menu": "MENU",
		"common.none": "None",
		"common.roster": "ROSTER",
		"common.skip": "SKIP",
		"common.pass_turn": "PASS TURN",
		"menu.new_game": "NEW GAME",
		"menu.continue": "CONTINUE",
		"menu.how_to_play": "HOW TO PLAY",
		"menu.settings": "SETTINGS",
		"menu.exit": "EXIT",
		"menu.footer": "A fictional intelligence simulation. v1.0",
		"settings.title": "SETTINGS",
		"settings.music": "Music Volume",
		"settings.sfx": "SFX Volume",
		"settings.haptics": "Haptic Feedback",
		"settings.large_text": "Large Text",
		"settings.reduce_motion": "Reduce Motion",
		"settings.language": "Language",
		"settings.reset": "RESET SAVE DATA",
		"settings.reset_confirm": "TAP AGAIN TO CONFIRM RESET",
		"settings.reset_done": "SAVE DATA CLEARED",
		"settings.about_title": "ABOUT",
		"settings.about_body": "Fictional and abstract. No real countries, agencies, or persons are depicted. Built with Godot Engine.",
		"new_game.title": "SELECT POSTURE",
		"new_game.hint": "Choose how much the world will forgive.",
		"new_game.begin": "BEGIN %s",
		"difficulty.0.name": "Rookie Desk",
		"difficulty.0.desc": "Forgiving. More funds, slower exposure, gentler events.",
		"difficulty.1.name": "Standard Watch",
		"difficulty.1.desc": "The intended experience. Balanced pressure.",
		"difficulty.2.name": "Black Room",
		"difficulty.2.desc": "Unforgiving. Thin resources, fast rival spread, harsh failures.",
		"game.turn": "TURN",
		"game.intel": "INTEL",
		"game.funds": "FUNDS",
		"game.trust": "TRUST",
		"game.cover": "COVER",
		"game.heat": "HEAT",
		"game.rival_meter": "RIVAL NETWORK",
		"game.global_meter": "GLOBAL EXPOSURE",
		"game.stability": "Stability %d",
		"game.momentum": "Momentum %d",
		"game.objective": "Goal: expose Rival Network before Global Exposure reaches 100.",
		"game.danger": "Danger: Global %d/100 | Trust %d | Lost regions %d/%d",
		"game.step_region": "Step 1: Select a region",
		"game.step_region_detail": "Tap a region node to open its dossier.",
		"game.step_next_region_detail": "Tap a region node to begin the next operation.",
		"game.step_review_region": "Step 2: Review region",
		"game.step_review_region_detail": "Choose Agent to assign work here.",
		"game.step_agent": "Step 2: Choose an agent",
		"game.step_agent_detail": "Pick the agent whose skills fit the job.",
		"game.step_operation": "Step 3: Choose an operation",
		"game.step_operation_detail": "Check cost, chance, Heat, and expected effect.",
		"game.step_result": "Step 4: Review the result",
		"game.step_result_detail": "Read what changed, then adapt next turn.",
		"game.step_result_next_detail": "Read what changed, then choose the next region.",
		"game.step_pass_detail": "Agents rest while the rival network moves.",
		"game.incoming_report": "Incoming report",
		"game.incoming_report_detail": "Choose a response, then review the consequences.",
		"game.directive_title": "DIRECTIVE",
		"game.directive_body": "Expose the Rival Network before Global Exposure reaches 100. Select a region, assign an agent, then run an operation. Build local networks and use Trace Rival Cell to progress toward victory.",
		"game.no_consequence": "No measurable consequences. Yet.",
		"game.pass_debrief_title": "Holding Pattern - agents rest",
		"game.verdict_success": "SUCCESS",
		"game.verdict_near_miss": "NEAR MISS",
		"game.verdict_failure": "FAILURE",
		"game.result_title": "%s - %s (%d%% chance, roll %d)",
		"region.classification": "Classification: %s",
		"region.unknown": "UNKNOWN",
		"region.intel_level": "Intel Level %d/3",
		"region.collapsed": "REGION COLLAPSED. No further operations possible here.",
		"region.stability": "Stability",
		"region.rival": "Rival Influence",
		"region.surveillance": "Surveillance",
		"region.pressure": "Public Pressure",
		"region.network": "Local Network",
		"region.opportunity": "Opportunity",
		"region.need_intel": "Need Intel",
		"region.map_signals_hint": "Run Map Signals here to reveal more.",
		"region.choose_agent": "CHOOSE AGENT",
		"agent.title": "AGENT ROSTER",
		"agent.select_title": "SELECT AGENT",
		"agent.roster_hint": "Review fatigue, traits, and skill coverage.",
		"agent.select_hint": "Choose one agent for the next operation.",
		"agent.level_short": "LV %d",
		"agent.trait": "Trait: %s",
		"agent.fatigue_status": "Fatigue %d / %s",
		"agent.ready": "Ready",
		"agent.strained": "Strained",
		"agent.select": "SELECT AGENT",
		"operation.title": "SELECT OPERATION",
		"operation.choose": "CHOOSE AN OPERATION",
		"operation.chance": "Chance %d%%",
		"operation.cost": "Cost",
		"operation.heat": "Heat",
		"operation.effect": "Effect",
		"operation.insufficient": "Insufficient resources.",
		"operation.run": "RUN OPERATION",
		"debrief.title": "OPERATION DEBRIEF",
		"debrief.global": "GLOBAL",
		"debrief.rival": "RIVAL",
		"debrief.heat": "HEAT",
		"debrief.funds": "FUNDS",
		"debrief.more": "%d additional changes recorded.",
		"event.strip": "INCOMING REPORT / %s",
		"tone.pressure": "PRESSURE",
		"tone.internal": "INTERNAL",
		"tone.rival": "RIVAL",
		"tone.world": "WORLD",
		"tone.opportunity": "OPPORTUNITY",
		"win.title": "NETWORK EXPOSED",
		"win.fallback": "Victory.",
		"loss.title": "DIRECTORATE DOWN",
		"loss.fallback": "The campaign has ended.",
		"end.reason.win": "The rival network has been fully exposed. Its structure is public, its cover gone.",
		"end.reason.global": "Global Exposure reached the point of no return. The crisis is now irreversible.",
		"end.reason.trust": "Agency Trust collapsed. The Directorate has been dissolved by emergency decree.",
		"end.reason.collapse": "Five regions have collapsed. The map you were protecting no longer exists.",
		"end.reason.funds": "The Directorate is insolvent. Operations ceased; the rival moves unopposed.",
		"end.turns": "Turns survived: %d",
		"end.ops": "Operations run: %d (%d successful)",
		"end.events": "Events faced: %d",
		"end.regions": "Regions lost: %d",
		"end.rival": "Rival network exposed: %d%%",
		"end.posture": "Posture: %s",
		"end.new_campaign": "NEW CAMPAIGN",
		"end.try_again": "TRY AGAIN",
		"tutorial.region": "Welcome, Director. Tap any region node on the map to open its dossier.",
		"tutorial.region_read": "This is the region dossier. Stability, Rival Influence and Surveillance decide how risky work here will be. Tap CHOOSE AGENT.",
		"tutorial.roster": "Every operation needs an agent. This is your roster.",
		"tutorial.agent": "Each agent is better at some work than others. Select any agent to continue.",
		"tutorial.map_signals": "Operations show cost, odds and Heat before you commit. Choose MAP SIGNALS - the safest way to learn a region.",
		"tutorial.resolve": "Run the operation and read the debrief.",
		"tutorial.intel": "INTEL is your analytical currency. Spend it on Deep Analysis and predictions. Earn it by mapping signals. (Tap to continue)",
		"tutorial.heat": "HEAT is how visible you are. High Heat feeds Global Exposure and triggers hostile events. Cool it down before it burns you. (Tap to continue)",
		"tutorial.rival": "RIVAL NETWORK EXPOSURE is your victory meter. Build local networks, then run Trace Rival Cell to push it to 100. (Tap to continue)",
		"tutorial.finish": "The rest is judgment. Watch the map, spend carefully, and expose them before the world unravels. Good luck, Director. (Tap to finish)",
		"how.title": "HOW TO PLAY",
		"how.mission.title": "Mission",
		"how.mission.body": "Expose the Rival Network before Global Exposure reaches 100.",
		"how.mission.losses": "Failure comes from Global Exposure at 100, Agency Trust at 0, or too many collapsed regions.",
		"how.flow.title": "Turn Flow",
		"how.flow.1": "Select a region",
		"how.flow.2": "Choose an agent",
		"how.flow.3": "Choose an operation",
		"how.flow.4": "Review the result",
		"how.flow.5": "Respond to events",
		"how.flow.6": "Repeat",
		"how.resources.title": "Resources",
		"how.res.intel": "Used for analysis and some operations. Earn it by mapping signals.",
		"how.res.funds": "Pays operation costs and agent upkeep.",
		"how.res.trust": "Your mandate. If Trust reaches 0, the run ends.",
		"how.res.cover": "Absorbs fallout when operations go badly.",
		"how.res.heat": "Your visibility. High Heat accelerates Global Exposure.",
		"how.global.title": "Global Situation",
		"how.global.rival": "Victory meter. Push Rival Network Exposure to 100.",
		"how.global.exposure": "Loss meter. If Global Exposure reaches 100, the crisis wins.",
		"how.global.stability_label": "STABILITY",
		"how.global.momentum_label": "MOMENTUM",
		"how.global.stability": "Average regional stability. Low stability means collapse risk.",
		"how.global.momentum": "How fast the rival network spreads pressure.",
		"how.first.title": "First Moves",
		"how.first.1": "Tap a region and read its dossier.",
		"how.first.2": "Assign an agent whose skills fit the operation.",
		"how.first.3": "Use Map Signals or Build Local Network early.",
		"how.first.4": "Use Trace Rival Cell when odds are favorable.",
		"how.tips.title": "Operational Tips",
		"how.tip.1": "High Heat increases danger.",
		"how.tip.2": "Stable regions are easier to manage.",
		"how.tip.3": "Local networks improve future operations.",
		"how.tip.4": "Do not ignore rising global pressure.",
	},
	"tr": {
		"brand.subtitle": "SESSİZ HARİTACILIK",
		"common.back": "GERİ",
		"common.begin": "BAŞLA",
		"common.close": "KAPAT",
		"common.continue": "DEVAM",
		"common.main_menu": "ANA MENÜ",
		"common.menu": "MENÜ",
		"common.none": "Yok",
		"common.roster": "KADRO",
		"common.skip": "GEÇ",
		"common.pass_turn": "TURU GEÇ",
		"menu.new_game": "YENİ OYUN",
		"menu.continue": "DEVAM ET",
		"menu.how_to_play": "NASIL OYNANIR",
		"menu.settings": "AYARLAR",
		"menu.exit": "ÇIKIŞ",
		"menu.footer": "Kurgusal istihbarat simülasyonu. v1.0",
		"settings.title": "AYARLAR",
		"settings.music": "Müzik Ses Düzeyi",
		"settings.sfx": "Efekt Ses Düzeyi",
		"settings.haptics": "Titreşim Geri Bildirimi",
		"settings.large_text": "Büyük Yazı",
		"settings.reduce_motion": "Hareketi Azalt",
		"settings.language": "Dil",
		"settings.reset": "KAYIT VERİSİNİ SIFIRLA",
		"settings.reset_confirm": "SIFIRLAMAK İÇİN TEKRAR DOKUN",
		"settings.reset_done": "KAYIT VERİSİ TEMİZLENDİ",
		"settings.about_title": "HAKKINDA",
		"settings.about_body": "Tamamen kurgusal ve soyuttur. Gerçek ülkeler, kurumlar veya kişiler tasvir edilmez. Godot Engine ile yapılmıştır.",
		"new_game.title": "DURUŞ SEÇ",
		"new_game.hint": "Dünyanın hatalara ne kadar tolerans göstereceğini seç.",
		"new_game.begin": "%s BAŞLAT",
		"difficulty.0.name": "Acemi Masa",
		"difficulty.0.desc": "Daha hoşgörülü. Daha fazla fon, daha yavaş iz, daha yumuşak olaylar.",
		"difficulty.1.name": "Standart Nöbet",
		"difficulty.1.desc": "Önerilen deneyim. Dengeli baskı.",
		"difficulty.2.name": "Kara Oda",
		"difficulty.2.desc": "Acımasız. Az kaynak, hızlı rakip yayılımı, sert hatalar.",
		"game.turn": "TUR",
		"game.intel": "İST",
		"game.funds": "FON",
		"game.trust": "GÜVEN",
		"game.cover": "ÖRTÜ",
		"game.heat": "ISI",
		"game.rival_meter": "RAKİP AĞ",
		"game.global_meter": "KÜRESEL İZ",
		"game.stability": "İstikrar %d",
		"game.momentum": "İvme %d",
		"game.objective": "Hedef: Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar.",
		"game.danger": "Tehlike: Küresel %d/100 | Güven %d | Kayıp bölge %d/%d",
		"game.step_region": "Adım 1: Bölge seç",
		"game.step_region_detail": "Dosyasını açmak için haritadaki bir bölgeye dokun.",
		"game.step_next_region_detail": "Sonraki operasyon için bir bölgeye dokun.",
		"game.step_review_region": "Adım 2: Bölgeyi incele",
		"game.step_review_region_detail": "Burada çalışacak ajanı seç.",
		"game.step_agent": "Adım 2: Ajan seç",
		"game.step_agent_detail": "İş için uygun becerilere sahip ajanı seç.",
		"game.step_operation": "Adım 3: Operasyon seç",
		"game.step_operation_detail": "Maliyet, şans, Isı ve beklenen etkiyi kontrol et.",
		"game.step_result": "Adım 4: Sonucu incele",
		"game.step_result_detail": "Neyin değiştiğini oku, sonraki tura uyum sağla.",
		"game.step_result_next_detail": "Neyin değiştiğini oku, sonra yeni bölge seç.",
		"game.step_pass_detail": "Ajanlar dinlenirken rakip ağ hareket eder.",
		"game.incoming_report": "Gelen rapor",
		"game.incoming_report_detail": "Bir yanıt seç, sonra sonuçları incele.",
		"game.directive_title": "DİREKTİF",
		"game.directive_body": "Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar. Bir bölge seç, ajan ata ve operasyon yürüt. Zafer için yerel ağlar kur, sonra Rakip Hücreyi İzle operasyonunu kullan.",
		"game.no_consequence": "Ölçülebilir bir sonuç yok. Şimdilik.",
		"game.pass_debrief_title": "Bekleme Durumu - ajanlar dinleniyor",
		"game.verdict_success": "BAŞARILI",
		"game.verdict_near_miss": "KIL PAYI",
		"game.verdict_failure": "BAŞARISIZ",
		"game.result_title": "%s - %s (%d%% şans, zar %d)",
		"region.classification": "Sınıflandırma: %s",
		"region.unknown": "BİLİNMİYOR",
		"region.intel_level": "İstihbarat Seviyesi %d/3",
		"region.collapsed": "BÖLGE ÇÖKTÜ. Burada artık operasyon yapılamaz.",
		"region.stability": "İstikrar",
		"region.rival": "Rakip Etkisi",
		"region.surveillance": "Gözetim",
		"region.pressure": "Kamu Baskısı",
		"region.network": "Yerel Ağ",
		"region.opportunity": "Fırsat",
		"region.need_intel": "İstihbarat gerekli",
		"region.map_signals_hint": "Daha fazlasını açmak için burada Sinyalleri Haritala.",
		"region.choose_agent": "AJAN SEÇ",
		"agent.title": "AJAN KADROSU",
		"agent.select_title": "AJAN SEÇ",
		"agent.roster_hint": "Yorgunluk, özellik ve beceri dağılımını incele.",
		"agent.select_hint": "Sonraki operasyon için bir ajan seç.",
		"agent.level_short": "SV %d",
		"agent.trait": "Özellik: %s",
		"agent.fatigue_status": "Yorgunluk %d / %s",
		"agent.ready": "Hazır",
		"agent.strained": "Zorlanmış",
		"agent.select": "AJAN SEÇ",
		"operation.title": "OPERASYON SEÇ",
		"operation.choose": "BİR OPERASYON SEÇ",
		"operation.chance": "Şans %d%%",
		"operation.cost": "Maliyet",
		"operation.heat": "Isı",
		"operation.effect": "Etki",
		"operation.insufficient": "Kaynaklar yetersiz.",
		"operation.run": "OPERASYONU YÜRÜT",
		"debrief.title": "OPERASYON RAPORU",
		"debrief.global": "KÜRESEL",
		"debrief.rival": "RAKİP",
		"debrief.heat": "ISI",
		"debrief.funds": "FON",
		"debrief.more": "%d ek değişiklik kaydedildi.",
		"event.strip": "GELEN RAPOR / %s",
		"tone.pressure": "BASKI",
		"tone.internal": "İÇ",
		"tone.rival": "RAKİP",
		"tone.world": "DÜNYA",
		"tone.opportunity": "FIRSAT",
		"win.title": "AĞ AÇIĞA ÇIKTI",
		"win.fallback": "Zafer.",
		"loss.title": "DİREKTÖRLÜK DÜŞTÜ",
		"loss.fallback": "Sefer sona erdi.",
		"end.reason.win": "Rakip ağ tamamen açığa çıkarıldı. Yapısı görünür, örtüsü yok oldu.",
		"end.reason.global": "Küresel İz geri dönüşsüz noktaya ulaştı. Kriz artık durdurulamaz.",
		"end.reason.trust": "Kurum Güveni çöktü. Direktörlük acil kararnameyle dağıtıldı.",
		"end.reason.collapse": "Beş bölge çöktü. Korumaya çalıştığın harita artık yok.",
		"end.reason.funds": "Direktörlük ödeme gücünü yitirdi. Operasyonlar durdu; rakip karşılıksız ilerliyor.",
		"end.turns": "Hayatta kalınan tur: %d",
		"end.ops": "Yürütülen operasyon: %d (%d başarılı)",
		"end.events": "Karşılaşılan olay: %d",
		"end.regions": "Kaybedilen bölge: %d",
		"end.rival": "Açığa çıkarılan rakip ağ: %d%%",
		"end.posture": "Duruş: %s",
		"end.new_campaign": "YENİ SEFER",
		"end.try_again": "TEKRAR DENE",
		"tutorial.region": "Hoş geldin Direktör. Dosyasını açmak için haritadaki herhangi bir bölgeye dokun.",
		"tutorial.region_read": "Bu bölge dosyası. İstikrar, Rakip Etkisi ve Gözetim burada çalışmanın riskini belirler. AJAN SEÇ'e dokun.",
		"tutorial.roster": "Her operasyon bir ajan ister. Bu senin kadron.",
		"tutorial.agent": "Ajanlar farklı işlerde güçlüdür. Devam etmek için bir ajan seç.",
		"tutorial.map_signals": "Operasyonlar onaydan önce maliyet, şans ve Isı gösterir. Bölgeyi öğrenmenin en güvenli yolu olan MAP SIGNALS'i seç.",
		"tutorial.resolve": "Operasyonu yürüt ve raporu oku.",
		"tutorial.intel": "İSTİHBARAT analitik kaynağındır. Deep Analysis ve öngörüler için harcanır. Sinyalleri haritalayarak kazanırsın. (Devam etmek için dokun)",
		"tutorial.heat": "ISI ne kadar görünür olduğundur. Yüksek Isı, Küresel İz'i besler ve düşmanca olayları çağırır. Tehlikeye dönüşmeden azalt. (Devam etmek için dokun)",
		"tutorial.rival": "RAKİP AĞ MARUZİYETİ zafer göstergendir. Yerel ağlar kur, sonra Trace Rival Cell ile 100'e taşı. (Devam etmek için dokun)",
		"tutorial.finish": "Gerisi muhakeme. Haritayı izle, dikkatli harca ve dünya dağılmadan ağı açığa çıkar. İyi şanslar Direktör. (Bitirmek için dokun)",
		"how.title": "NASIL OYNANIR",
		"how.mission.title": "Misyon",
		"how.mission.body": "Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar.",
		"how.mission.losses": "Küresel İz 100'e ulaşırsa, Kurum Güveni 0 olursa veya çok fazla bölge çökerse kaybedersin.",
		"how.flow.title": "Tur Akışı",
		"how.flow.1": "Bölge seç",
		"how.flow.2": "Ajan seç",
		"how.flow.3": "Operasyon seç",
		"how.flow.4": "Sonucu incele",
		"how.flow.5": "Olaylara yanıt ver",
		"how.flow.6": "Tekrarla",
		"how.resources.title": "Kaynaklar",
		"how.res.intel": "Analiz ve bazı operasyonlar için kullanılır. Sinyal haritalayarak kazanılır.",
		"how.res.funds": "Operasyon maliyetleri ve ajan giderlerini karşılar.",
		"how.res.trust": "Yetki zeminin. Güven 0 olursa sefer biter.",
		"how.res.cover": "Operasyonlar ters gittiğinde etkiyi azaltır.",
		"how.res.heat": "Görünürlüğün. Yüksek Isı, Küresel İz'i hızlandırır.",
		"how.global.title": "Küresel Durum",
		"how.global.rival": "Zafer göstergesi. Rakip Ağ Maruziyetini 100'e taşı.",
		"how.global.exposure": "Kayıp göstergesi. Küresel İz 100 olursa kriz kazanır.",
		"how.global.stability_label": "İSTİKRAR",
		"how.global.momentum_label": "İVME",
		"how.global.stability": "Ortalama bölge istikrarı. Düşük istikrar çökme riski demektir.",
		"how.global.momentum": "Rakip ağın baskıyı ne kadar hızlı yaydığını gösterir.",
		"how.first.title": "İlk Hamleler",
		"how.first.1": "Bir bölgeye dokun ve dosyasını oku.",
		"how.first.2": "Operasyona uygun becerilere sahip ajan ata.",
		"how.first.3": "Erken oyunda Sinyalleri Haritala veya Yerel Ağ Kur.",
		"how.first.4": "Şans uygunken Rakip Hücreyi İzle operasyonunu kullan.",
		"how.tips.title": "Operasyon İpuçları",
		"how.tip.1": "Yüksek Isı tehlikeyi artırır.",
		"how.tip.2": "İstikrarlı bölgeleri yönetmek daha kolaydır.",
		"how.tip.3": "Yerel ağlar sonraki operasyonları güçlendirir.",
		"how.tip.4": "Yükselen küresel baskıyı görmezden gelme.",
	},
}

var _locale: String = DEFAULT_LOCALE


func _ready() -> void:
	_locale = _normalize_locale(SettingsManager.language_code)


func current_locale() -> String:
	return _locale


func language_label(locale: String = "") -> String:
	var code := _locale if locale == "" else locale
	for entry in LANGUAGES:
		if entry["code"] == code:
			return String(entry["label"])
	return "English"


func language_codes() -> Array[String]:
	var out: Array[String] = []
	for entry in LANGUAGES:
		out.append(String(entry["code"]))
	return out


func set_locale(locale: String) -> void:
	var next := _normalize_locale(locale)
	if _locale == next:
		return
	_locale = next
	SettingsManager.language_code = next
	SettingsManager.save_settings()
	locale_changed.emit(_locale)


func t(key: String, args: Array = []) -> String:
	var table: Dictionary = TEXT.get(_locale, TEXT[DEFAULT_LOCALE])
	var fallback: Dictionary = TEXT[DEFAULT_LOCALE]
	var value: String = String(table.get(key, fallback.get(key, key)))
	if args.is_empty():
		return value
	return value % args


func _normalize_locale(locale: String) -> String:
	for entry in LANGUAGES:
		if entry["code"] == locale:
			return locale
	return DEFAULT_LOCALE
