extends RefCounted
## Data-backed player-facing text kept separate from the core UI catalog.
## Keys are derived from stable gameplay IDs; gameplay data remains unchanged.

const TEXT := {
	"en": {
		"region_name.kareth": "Kareth Basin",
		"region_name.vorn": "Vorn Coast",
		"region_name.halden": "Halden Grid",
		"region_name.oris": "Oris Gate",
		"region_name.namar": "Namar Verge",
		"region_name.ceyr": "Ceyr Line",
		"region_name.talric": "Talric Ward",
		"region_name.estra": "Estra Vale",
		"region_name.rovan": "Rovan Span",
		"region_name.silen": "Silen Reach",
		"region_name.damar": "Damar Quay",
		"region_name.arken": "Arken Hollow",
		"region_name.nareth": "Nareth Coil",
		"region_name.vey": "Vey Coast",
		"region_name.solmar": "Solmar Ring",
		"region_name.istren": "Istren Fold",
		"agent.sela.bio": "Reads pattern noise the way others read headlines. Rarely leaves the map room.",
		"agent.doran.bio": "Moves through crowded corridors without leaving a trace on anyone's memory.",
		"agent.iren.bio": "Keeps every channel open and every promise vague. Never gambles with trust.",
		"agent.maro.bio": "The best listener the Directorate can afford. Barely.",
		"agent.vessa.bio": "Has walked out of three collapsing rooms with the paperwork intact.",
		"agent.aster.bio": "Knows everyone worth knowing. Half of them want something in return.",
		"event.result.resource_delta": "%s %s",
		"event.result.region_stability": "%s: Stability %s%d",
		"event.result.region_rival": "%s: Rival Influence %s%d",
		"event.result.region_pressure": "%s: Public Pressure %s%d",
		"event.result.rival_reveal": "Rival presence in %s charted (Intel Level 2).",
		"event.result.all_stability": "All regions: Stability %s%d",
		"event.result.agent_fatigue": "%s: Fatigue +%d",
		"event.result.agent_rest": "%s recovers %d Fatigue.",
		"event.result.all_agent_rest": "All agents recover %d Fatigue.",
		"resource.intel": "Intel",
		"resource.funds": "Funds",
		"resource.trust": "Trust",
		"resource.heat": "Heat",
		"resource.cover": "Cover",
		"resource.global_exposure": "Global Exposure",
		"resource.rival_momentum": "Rival Spread",
		"resource.rival_exposure": "Rival Network Uncovered",

		"event.leaked_briefing.title": "Leaked Briefing",
		"event.leaked_briefing.desc": "A summary of Directorate activity surfaces in an open forum. It is vague, but it is ours.",
		"event.leaked_briefing.choice.0.text": "Deny everything, publicly.",
		"event.leaked_briefing.choice.0.note": "-8 Heat, -6 Trust",
		"event.leaked_briefing.choice.1.text": "Say nothing. Let it fade.",
		"event.leaked_briefing.choice.1.note": "+5 Global Exposure",
		"event.leaked_briefing.choice.2.text": "Spend Intel to trace the leak.",
		"event.leaked_briefing.choice.2.note": "-8 Intel, -12 Heat",
		"event.unstable_contact.title": "Unstable Contact",
		"event.unstable_contact.desc": "A local source demands double payment and hints they have other buyers.",
		"event.unstable_contact.choice.0.text": "Pay them off.",
		"event.unstable_contact.choice.0.note": "-15 Funds",
		"event.unstable_contact.choice.1.text": "Cut them loose.",
		"event.unstable_contact.choice.1.note": "+Rival Influence in one region, +4 Heat",
		"event.false_pattern.title": "False Pattern",
		"event.false_pattern.desc": "Analysis flags a promising signal cluster. Something about it feels planted.",
		"event.false_pattern.choice.0.text": "Chase it anyway.",
		"event.false_pattern.choice.0.note": "-6 Intel, +4 Rival Network Uncovered",
		"event.false_pattern.choice.1.text": "Discard the cluster.",
		"event.false_pattern.choice.1.note": "+3 Rival Spread",
		"event.false_pattern.choice.2.text": "Feed it false interest.",
		"event.false_pattern.choice.2.note": "+6 Heat, -4 Rival Spread",
		"event.budget_hearing.title": "Budget Hearing",
		"event.budget_hearing.desc": "The oversight committee wants numbers. The numbers are defensible, barely.",
		"event.budget_hearing.choice.0.text": "Full transparency.",
		"event.budget_hearing.choice.0.note": "+8 Trust, -10 Funds",
		"event.budget_hearing.choice.1.text": "Creative accounting.",
		"event.budget_hearing.choice.1.note": "+15 Funds, -8 Trust",
		"event.regional_panic.title": "Regional Panic",
		"event.regional_panic.desc": "Rumors of an unseen crisis spread through a fragile region. Markets flinch.",
		"event.regional_panic.choice.0.text": "Issue calming statements.",
		"event.regional_panic.choice.0.note": "+Stability in one region, +5 Heat",
		"event.regional_panic.choice.1.text": "Stay out of it.",
		"event.regional_panic.choice.1.note": "-Stability in one region",
		"event.rival_broadcast.title": "Rival Broadcast",
		"event.rival_broadcast.desc": "An anonymous transmission mocks the Directorate by name. It is designed to provoke.",
		"event.rival_broadcast.choice.0.text": "Trace the transmission.",
		"event.rival_broadcast.choice.0.note": "-5 Intel, +6 Rival Network Uncovered, +4 Heat",
		"event.rival_broadcast.choice.1.text": "Ignore the bait.",
		"event.rival_broadcast.choice.1.note": "-4 Trust",
		"event.quiet_breakthrough.title": "Quiet Breakthrough",
		"event.quiet_breakthrough.desc": "A junior analyst finds an overlap between two dead files. It might be nothing.",
		"event.quiet_breakthrough.choice.0.text": "Fund a follow-up.",
		"event.quiet_breakthrough.choice.0.note": "-10 Funds, +12 Intel",
		"event.quiet_breakthrough.choice.1.text": "Archive it for later.",
		"event.quiet_breakthrough.choice.1.note": "+3 Intel",
		"event.double_signal.title": "Double Signal",
		"event.double_signal.desc": "Two identical signatures appear in distant regions at the same hour. One is a decoy.",
		"event.double_signal.choice.0.text": "Split resources, cover both.",
		"event.double_signal.choice.0.note": "-12 Funds, +5 Rival Network Uncovered",
		"event.double_signal.choice.1.text": "Commit to one.",
		"event.double_signal.choice.1.note": "+8 Rival Network Uncovered, +Rival Influence in one region",
		"event.double_signal.choice.2.text": "Watch and wait.",
		"event.double_signal.choice.2.note": "+3 Rival Spread",
		"event.public_scrutiny.title": "Public Scrutiny",
		"event.public_scrutiny.desc": "An investigative outlet starts asking careful questions about budget lines.",
		"event.public_scrutiny.choice.0.text": "Cooperate within limits.",
		"event.public_scrutiny.choice.0.note": "+5 Trust, +5 Heat",
		"event.public_scrutiny.choice.1.text": "Stonewall.",
		"event.public_scrutiny.choice.1.note": "-5 Heat, -7 Trust",
		"event.asset_burnout.title": "Asset Burnout",
		"event.asset_burnout.desc": "One of your people has been running on fumes for weeks. It shows.",
		"event.asset_burnout.choice.0.text": "Force a rest cycle.",
		"event.asset_burnout.choice.0.note": "One agent recovers Fatigue",
		"event.asset_burnout.choice.1.text": "Push through.",
		"event.asset_burnout.choice.1.note": "+Fatigue on one agent, +5 Intel",
		"event.map_discrepancy.title": "Map Discrepancy",
		"event.map_discrepancy.desc": "Field reports and satellite composites disagree about one region's quiet zones.",
		"event.map_discrepancy.choice.0.text": "Send a verification sweep.",
		"event.map_discrepancy.choice.0.note": "-8 Funds, reveal one regional identity",
		"event.map_discrepancy.choice.1.text": "Trust the field reports.",
		"event.map_discrepancy.choice.1.note": "+2 Intel",
		"event.committee_pressure.title": "Committee Pressure",
		"event.committee_pressure.desc": "The committee wants visible results this quarter, not careful groundwork.",
		"event.committee_pressure.choice.0.text": "Promise fast results.",
		"event.committee_pressure.choice.0.note": "+8 Trust, +8 Heat",
		"event.committee_pressure.choice.1.text": "Defend the slow approach.",
		"event.committee_pressure.choice.1.note": "-5 Trust, +8 Cover",
		"event.silent_defection.title": "Silent Defection",
		"event.silent_defection.desc": "A mid-level rival courier stops appearing in intercepts. They may want out.",
		"event.silent_defection.choice.0.text": "Offer safe passage.",
		"event.silent_defection.choice.0.note": "-15 Funds, +10 Rival Network Uncovered",
		"event.silent_defection.choice.1.text": "Too risky. Observe only.",
		"event.silent_defection.choice.1.note": "+6 Intel",
		"event.silent_defection.choice.2.text": "Leak their name to the rival.",
		"event.silent_defection.choice.2.note": "-6 Rival Spread, -6 Trust",
		"event.dead_channel.title": "Dead Channel",
		"event.dead_channel.desc": "A reliable listening channel goes silent overnight. No interference, no static. Nothing.",
		"event.dead_channel.choice.0.text": "Rebuild it quietly.",
		"event.dead_channel.choice.0.note": "-10 Funds, +3 Heat",
		"event.dead_channel.choice.1.text": "Assume it is burned.",
		"event.dead_channel.choice.1.note": "-5 Intel, +5 Cover",
		"event.fractured_report.title": "Fractured Report",
		"event.fractured_report.desc": "Two trusted analysts submit contradictory assessments of the same region.",
		"event.fractured_report.choice.0.text": "Commission a third review.",
		"event.fractured_report.choice.0.note": "-6 Funds, +8 Intel",
		"event.fractured_report.choice.1.text": "Average the findings.",
		"event.fractured_report.choice.1.note": "-Stability in one region",
		"event.emergency_session.title": "Emergency Session",
		"event.emergency_session.desc": "The committee convenes at night. Global indicators have crossed a quiet threshold.",
		"event.emergency_session.choice.0.text": "Request emergency powers.",
		"event.emergency_session.choice.0.note": "+20 Funds, -10 Trust",
		"event.emergency_session.choice.1.text": "Present a de-escalation plan.",
		"event.emergency_session.choice.1.note": "-6 Global Exposure, -12 Funds",
		"event.shadow_ledger.title": "Shadow Ledger",
		"event.shadow_ledger.desc": "A recovered ledger maps part of the rival's funding chain, in a cipher you half-know.",
		"event.shadow_ledger.choice.0.text": "Full decryption effort.",
		"event.shadow_ledger.choice.0.note": "-10 Intel, +9 Rival Network Uncovered",
		"event.shadow_ledger.choice.1.text": "Sell fragments to allies.",
		"event.shadow_ledger.choice.1.note": "+18 Funds, +4 Rival Spread",
		"event.data_fog.title": "Data Fog",
		"event.data_fog.desc": "Signal quality degrades across several corridors. Every feed is suddenly less certain.",
		"event.data_fog.choice.0.text": "Pay for clean relays.",
		"event.data_fog.choice.0.note": "-12 Funds",
		"event.data_fog.choice.1.text": "Work with degraded data.",
		"event.data_fog.choice.1.note": "-6 Intel",
		"event.rumor_storm.title": "Local Rumor Storm",
		"event.rumor_storm.desc": "A fabricated story about foreign observers spreads through one region's districts.",
		"event.rumor_storm.choice.0.text": "Counter with facts.",
		"event.rumor_storm.choice.0.note": "-8 Funds, -Public Pressure in one region",
		"event.rumor_storm.choice.1.text": "Let it burn out.",
		"event.rumor_storm.choice.1.note": "+Public Pressure, -Stability in one region",
		"event.signal_contamination.title": "Signal Contamination",
		"event.signal_contamination.desc": "Your intercept archive shows signs of deliberate poisoning. Weeks of data are suspect.",
		"event.signal_contamination.choice.0.text": "Purge the archive.",
		"event.signal_contamination.choice.0.note": "-10 Intel, +6 Cover",
		"event.signal_contamination.choice.1.text": "Flag and keep everything.",
		"event.signal_contamination.choice.1.note": "+5 Rival Spread",
		"event.friendly_audit.title": "Courtesy Review",
		"event.friendly_audit.desc": "An allied bureau offers to review your exposure posture. Their help never comes free.",
		"event.friendly_audit.choice.0.text": "Accept the review.",
		"event.friendly_audit.choice.0.note": "-8 Global Exposure, -6 Intel",
		"event.friendly_audit.choice.1.text": "Decline politely.",
		"event.friendly_audit.choice.1.note": "+4 Cover",
		"event.cold_pitch.title": "Cold Pitch",
		"event.cold_pitch.desc": "A stranger leaves a one-line message at a dead drop: 'I can name three of them.'",
		"event.cold_pitch.choice.0.text": "Take the meeting.",
		"event.cold_pitch.choice.0.note": "+8 Rival Network Uncovered, +8 Heat",
		"event.cold_pitch.choice.1.text": "Test them first.",
		"event.cold_pitch.choice.1.note": "-5 Intel, +4 Rival Network Uncovered",
		"event.cold_pitch.choice.2.text": "Burn the drop.",
		"event.cold_pitch.choice.2.note": "+5 Cover",
		"event.budget_freeze.title": "Budget Freeze",
		"event.budget_freeze.desc": "Payments across the bureau are suspended pending review of an unrelated scandal.",
		"event.budget_freeze.choice.0.text": "Call in old favors.",
		"event.budget_freeze.choice.0.note": "+15 Funds, -5 Trust",
		"event.budget_freeze.choice.1.text": "Absorb the freeze.",
		"event.budget_freeze.choice.1.note": "+Fatigue on one agent",
		"event.overheard_name.title": "Overheard Name",
		"event.overheard_name.desc": "One of your cover identities is spoken aloud in an intercepted call.",
		"event.overheard_name.choice.0.text": "Retire the identity.",
		"event.overheard_name.choice.0.note": "-8 Cover, -10 Heat",
		"event.overheard_name.choice.1.text": "Keep it active as bait.",
		"event.overheard_name.choice.1.note": "+6 Rival Network Uncovered, +6 Global Exposure",
		"event.stability_grant.title": "Stability Grant",
		"event.stability_grant.desc": "A neutral development fund offers matching support for regional stabilization.",
		"event.stability_grant.choice.0.text": "Match the grant.",
		"event.stability_grant.choice.0.note": "-15 Funds, +4 Stability everywhere",
		"event.stability_grant.choice.1.text": "Decline the entanglement.",
		"event.stability_grant.choice.1.note": "No effect",
		"event.misfiled_dossier.title": "Misfiled Dossier",
		"event.misfiled_dossier.desc": "A sensitive dossier spent six days in the wrong archive. Someone may have read it.",
		"event.misfiled_dossier.choice.0.text": "Internal investigation.",
		"event.misfiled_dossier.choice.0.note": "-8 Funds, +4 Trust",
		"event.misfiled_dossier.choice.1.text": "Reclassify and move on.",
		"event.misfiled_dossier.choice.1.note": "+5 Heat",
		"event.rival_recruiter.title": "Rival Recruiter",
		"event.rival_recruiter.desc": "The rival network is quietly hiring in a region where you have contacts.",
		"event.rival_recruiter.choice.0.text": "Outbid them.",
		"event.rival_recruiter.choice.0.note": "-14 Funds, -Rival Influence in one region",
		"event.rival_recruiter.choice.1.text": "Plant one of yours in the queue.",
		"event.rival_recruiter.choice.1.note": "+6 Heat, +7 Rival Network Uncovered",
		"event.quiet_quarter.title": "Quiet Quarter",
		"event.quiet_quarter.desc": "For once, nothing is on fire. The silence is almost suspicious.",
		"event.quiet_quarter.choice.0.text": "Rest the roster.",
		"event.quiet_quarter.choice.0.note": "All agents recover Fatigue",
		"event.quiet_quarter.choice.1.text": "Press the advantage.",
		"event.quiet_quarter.choice.1.note": "+6 Intel, +4 Heat",
		"event.border_incident.title": "Border Incident",
		"event.border_incident.desc": "A minor clash at a regional checkpoint threatens to draw larger attention.",
		"event.border_incident.choice.0.text": "Mediate through channels.",
		"event.border_incident.choice.0.note": "-10 Funds, +Stability in one region",
		"event.border_incident.choice.1.text": "Document, do not intervene.",
		"event.border_incident.choice.1.note": "+5 Intel, -Stability in one region",
		"event.encrypted_gift.title": "Encrypted Gift",
		"event.encrypted_gift.desc": "An anonymous parcel contains a storage device. It is either treasure or a trap.",
		"event.encrypted_gift.choice.0.text": "Open it in isolation.",
		"event.encrypted_gift.choice.0.note": "+10 Intel, +5 Heat",
		"event.encrypted_gift.choice.1.text": "Destroy it unopened.",
		"event.encrypted_gift.choice.1.note": "+4 Cover",
		"event.collapsed_echo.title": "Echoes of Collapse",
		"event.collapsed_echo.desc": "A collapsed region's disorder is spilling into its neighbors' markets and streets.",
		"event.collapsed_echo.choice.0.text": "Fund containment corridors.",
		"event.collapsed_echo.choice.0.note": "-18 Funds, +3 Stability everywhere",
		"event.collapsed_echo.choice.1.text": "Accept the drift.",
		"event.collapsed_echo.choice.1.note": "-3 Stability everywhere",
		"event.old_alliance_call.title": "An Old Understanding",
		"event.old_alliance_call.desc": "A retired counterpart from a friendlier era offers a private word of guidance.",
		"event.old_alliance_call.choice.0.text": "Meet them.",
		"event.old_alliance_call.choice.0.note": "+10 Trust, +3 Heat",
		"event.old_alliance_call.choice.1.text": "Some doors stay closed.",
		"event.old_alliance_call.choice.1.note": "No effect",
		"event.pattern_bleed.title": "Pattern Bleed",
		"event.pattern_bleed.desc": "Your own operational rhythm is becoming predictable. Someone is charting you.",
		"event.pattern_bleed.choice.0.text": "Randomize schedules.",
		"event.pattern_bleed.choice.0.note": "+Fatigue on one agent, +8 Cover",
		"event.pattern_bleed.choice.1.text": "Maintain tempo.",
		"event.pattern_bleed.choice.1.note": "+4 Rival Spread",
		"event.press_leak_race.title": "Race to Print",
		"event.press_leak_race.desc": "A journalist calls for comment on a story that is eighty percent correct.",
		"event.press_leak_race.choice.0.text": "Trade access for delay.",
		"event.press_leak_race.choice.0.note": "-6 Intel, -5 Global Exposure",
		"event.press_leak_race.choice.1.text": "No comment.",
		"event.press_leak_race.choice.1.note": "+7 Global Exposure",
		"event.internal_doubt.title": "Internal Doubt",
		"event.internal_doubt.desc": "Senior staff quietly question whether the rival network even exists at this scale.",
		"event.internal_doubt.choice.0.text": "Share raw evidence.",
		"event.internal_doubt.choice.0.note": "-5 Intel, +8 Trust",
		"event.internal_doubt.choice.1.text": "Demand discipline.",
		"event.internal_doubt.choice.1.note": "-4 Trust, +Fatigue on one agent",
		"event.gray_donor.title": "The Gray Donor",
		"event.gray_donor.desc": "A private benefactor offers substantial funding with politely unstated expectations.",
		"event.gray_donor.choice.0.text": "Accept the funds.",
		"event.gray_donor.choice.0.note": "+30 Funds, +8 Heat, -5 Trust",
		"event.gray_donor.choice.1.text": "Refuse.",
		"event.gray_donor.choice.1.note": "+5 Trust",
		"event.night_signal.title": "Night Signal",
		"event.night_signal.desc": "A single strong burst transmission originates from a region you thought was quiet.",
		"event.night_signal.choice.0.text": "Triangulate immediately.",
		"event.night_signal.choice.0.note": "-8 Funds, reveal rival presence in one region",
		"event.night_signal.choice.1.text": "Log it and wait.",
		"event.night_signal.choice.1.note": "+Rival Influence in one region",
	},
	"tr": {
		"region_name.kareth": "Kareth Havzası",
		"region_name.vorn": "Vorn Kıyısı",
		"region_name.halden": "Halden Ağı",
		"region_name.oris": "Oris Geçidi",
		"region_name.namar": "Namar Eşiği",
		"region_name.ceyr": "Ceyr Hattı",
		"region_name.talric": "Talric Bölgesi",
		"region_name.estra": "Estra Vadisi",
		"region_name.rovan": "Rovan Uzantısı",
		"region_name.silen": "Silen Uzanımı",
		"region_name.damar": "Damar Rıhtımı",
		"region_name.arken": "Arken Çukuru",
		"region_name.nareth": "Nareth Sarmalı",
		"region_name.vey": "Vey Kıyısı",
		"region_name.solmar": "Solmar Halkası",
		"region_name.istren": "Istren Kıvrımı",
		"agent.sela.bio": "Örüntü gürültüsünü başkalarının manşet okuduğu gibi okur. Harita odasından nadiren çıkar.",
		"agent.doran.bio": "Kalabalık koridorlarda kimsenin hafızasında iz bırakmadan ilerler.",
		"agent.iren.bio": "Her kanalı açık, her sözü muğlak tutar. Güveni asla kumara yatırmaz.",
		"agent.maro.bio": "Direktörlüğün karşılayabildiği en iyi dinleyici. Zar zor.",
		"agent.vessa.bio": "Çökmekte olan üç odadan evrakları eksiksiz çıkarak ayrıldı.",
		"agent.aster.bio": "Tanımaya değer herkesi tanır. Yarısı karşılığında bir şey ister.",
		"event.result.resource_delta": "%s %s",
		"event.result.region_stability": "%s: İstikrar %s%d",
		"event.result.region_rival": "%s: Rakip Etkisi %s%d",
		"event.result.region_pressure": "%s: Kamuoyu Baskısı %s%d",
		"event.result.rival_reveal": "%s bölgesindeki rakip varlığı haritalandı (İstihbarat Seviyesi 2).",
		"event.result.all_stability": "Tüm bölgeler: İstikrar %s%d",
		"event.result.agent_fatigue": "%s: Yorgunluk +%d",
		"event.result.agent_rest": "%s, %d Yorgunluk giderdi.",
		"event.result.all_agent_rest": "Tüm ajanlar %d Yorgunluk giderdi.",
		"resource.intel": "İstihbarat",
		"resource.funds": "Bütçe",
		"resource.trust": "Kurum Güveni",
		"resource.heat": "Operasyon İzi",
		"resource.cover": "Gizlilik",
		"resource.global_exposure": "Küresel Risk",
		"resource.rival_momentum": "Rakip Yayılımı",
		"resource.rival_exposure": "Rakip Ağ Deşifresi",

		"event.leaked_briefing.title": "Sızan Brifing",
		"event.leaked_briefing.desc": "Direktörlük faaliyetlerinin bir özeti açık bir forumda ortaya çıktı. Muğlak ama bize ait.",
		"event.leaked_briefing.choice.0.text": "Her şeyi açıkça inkâr et.",
		"event.leaked_briefing.choice.0.note": "-8 Operasyon İzi, -6 Güven",
		"event.leaked_briefing.choice.1.text": "Sessiz kal. Sönmesini bekle.",
		"event.leaked_briefing.choice.1.note": "+5 Küresel Risk",
		"event.leaked_briefing.choice.2.text": "Sızıntıyı izlemek için İstihbarat harca.",
		"event.leaked_briefing.choice.2.note": "-8 İstihbarat, -12 Operasyon İzi",
		"event.unstable_contact.title": "İstikrarsız Temas",
		"event.unstable_contact.desc": "Yerel bir kaynak iki kat ödeme istiyor ve başka alıcıları olduğunu ima ediyor.",
		"event.unstable_contact.choice.0.text": "Parasını ver.",
		"event.unstable_contact.choice.0.note": "-15 Bütçe",
		"event.unstable_contact.choice.1.text": "Bağlantıyı kes.",
		"event.unstable_contact.choice.1.note": "Bir bölgede +Rakip Etkisi, +4 Operasyon İzi",
		"event.false_pattern.title": "Sahte Örüntü",
		"event.false_pattern.desc": "Analiz umut verici bir sinyal kümesi buldu. Birileri yerleştirmiş gibi duruyor.",
		"event.false_pattern.choice.0.text": "Yine de peşine düş.",
		"event.false_pattern.choice.0.note": "-6 İstihbarat, +4 Rakip Ağ Deşifresi",
		"event.false_pattern.choice.1.text": "Kümeyi gözden çıkar.",
		"event.false_pattern.choice.1.note": "+3 Rakip Yayılımı",
		"event.false_pattern.choice.2.text": "Sahte ilgiyle karşılık ver.",
		"event.false_pattern.choice.2.note": "+6 Operasyon İzi, -4 Rakip Yayılımı",
		"event.budget_hearing.title": "Bütçe Oturumu",
		"event.budget_hearing.desc": "Denetim komitesi rakamları istiyor. Rakamlar savunulabilir, zar zor.",
		"event.budget_hearing.choice.0.text": "Tam şeffaflık.",
		"event.budget_hearing.choice.0.note": "+8 Güven, -10 Bütçe",
		"event.budget_hearing.choice.1.text": "Yaratıcı muhasebe.",
		"event.budget_hearing.choice.1.note": "+15 Bütçe, -8 Güven",
		"event.regional_panic.title": "Bölgesel Panik",
		"event.regional_panic.desc": "Görünmeyen bir kriz söylentileri kırılgan bir bölgede yayılıyor. Piyasalar sarsıldı.",
		"event.regional_panic.choice.0.text": "Yatıştırıcı açıklamalar yap.",
		"event.regional_panic.choice.0.note": "Bir bölgede +İstikrar, +5 Operasyon İzi",
		"event.regional_panic.choice.1.text": "Karışma.",
		"event.regional_panic.choice.1.note": "Bir bölgede -İstikrar",
		"event.rival_broadcast.title": "Rakip Yayını",
		"event.rival_broadcast.desc": "Anonim bir yayın Direktörlükle adıyla alay ediyor. Amaç kışkırtmak.",
		"event.rival_broadcast.choice.0.text": "Yayını izle.",
		"event.rival_broadcast.choice.0.note": "-5 İstihbarat, +6 Rakip Ağ Deşifresi, +4 Operasyon İzi",
		"event.rival_broadcast.choice.1.text": "Yemi görmezden gel.",
		"event.rival_broadcast.choice.1.note": "-4 Güven",
		"event.quiet_breakthrough.title": "Sessiz Atılım",
		"event.quiet_breakthrough.desc": "Genç bir analist iki ölü dosya arasında kesişim buldu. Hiçbir şey olmayabilir.",
		"event.quiet_breakthrough.choice.0.text": "Takip çalışmasını finanse et.",
		"event.quiet_breakthrough.choice.0.note": "-10 Bütçe, +12 İstihbarat",
		"event.quiet_breakthrough.choice.1.text": "Sonrası için arşivle.",
		"event.quiet_breakthrough.choice.1.note": "+3 İstihbarat",
		"event.double_signal.title": "Çifte Sinyal",
		"event.double_signal.desc": "Aynı saatte uzak iki bölgede özdeş imzalar belirdi. Biri yem.",
		"event.double_signal.choice.0.text": "Kaynakları böl, ikisini de kapsa.",
		"event.double_signal.choice.0.note": "-12 Bütçe, +5 Rakip Ağ Deşifresi",
		"event.double_signal.choice.1.text": "Birine odaklan.",
		"event.double_signal.choice.1.note": "+8 Rakip Ağ Deşifresi, bir bölgede +Rakip Etkisi",
		"event.double_signal.choice.2.text": "İzle ve bekle.",
		"event.double_signal.choice.2.note": "+3 Rakip Yayılımı",
		"event.public_scrutiny.title": "Kamuoyu İncelemesi",
		"event.public_scrutiny.desc": "Bir araştırmacı yayın bütçe kalemleri hakkında dikkatli sorular soruyor.",
		"event.public_scrutiny.choice.0.text": "Sınırlar içinde iş birliği yap.",
		"event.public_scrutiny.choice.0.note": "+5 Güven, +5 Operasyon İzi",
		"event.public_scrutiny.choice.1.text": "Bilgi vermeyi reddet.",
		"event.public_scrutiny.choice.1.note": "-5 Operasyon İzi, -7 Güven",
		"event.asset_burnout.title": "Ajan Tükenmişliği",
		"event.asset_burnout.desc": "Ekibinden biri haftalardır tükenmiş halde çalışıyor. Artık belli oluyor.",
		"event.asset_burnout.choice.0.text": "Zorunlu dinlenme döngüsü başlat.",
		"event.asset_burnout.choice.0.note": "Bir ajan Yorgunluk giderir",
		"event.asset_burnout.choice.1.text": "Devam etmesini iste.",
		"event.asset_burnout.choice.1.note": "Bir ajana +Yorgunluk, +5 İstihbarat",
		"event.map_discrepancy.title": "Harita Tutarsızlığı",
		"event.map_discrepancy.desc": "Saha raporlarıyla uydu bileşimleri bir bölgenin sessiz alanları konusunda uyuşmuyor.",
		"event.map_discrepancy.choice.0.text": "Doğrulama taraması gönder.",
		"event.map_discrepancy.choice.0.note": "-8 Bütçe, bir bölgesel kimliği açığa çıkar",
		"event.map_discrepancy.choice.1.text": "Saha raporlarına güven.",
		"event.map_discrepancy.choice.1.note": "+2 İstihbarat",
		"event.committee_pressure.title": "Komite Baskısı",
		"event.committee_pressure.desc": "Komite dikkatli hazırlık değil, bu çeyrekte görünür sonuç istiyor.",
		"event.committee_pressure.choice.0.text": "Hızlı sonuç sözü ver.",
		"event.committee_pressure.choice.0.note": "+8 Güven, +8 Operasyon İzi",
		"event.committee_pressure.choice.1.text": "Yavaş yaklaşımı savun.",
		"event.committee_pressure.choice.1.note": "-5 Güven, +8 Gizlilik",
		"event.silent_defection.title": "Sessiz İltica",
		"event.silent_defection.desc": "Orta düzey bir rakip kurye dinlemelerde görünmez oldu. Ayrılmak istiyor olabilir.",
		"event.silent_defection.choice.0.text": "Güvenli geçiş teklif et.",
		"event.silent_defection.choice.0.note": "-15 Bütçe, +10 Rakip Ağ Deşifresi",
		"event.silent_defection.choice.1.text": "Fazla riskli. Yalnızca izle.",
		"event.silent_defection.choice.1.note": "+6 İstihbarat",
		"event.silent_defection.choice.2.text": "Adını rakibe sızdır.",
		"event.silent_defection.choice.2.note": "-6 Rakip Yayılımı, -6 Güven",
		"event.dead_channel.title": "Ölü Kanal",
		"event.dead_channel.desc": "Güvenilir bir dinleme kanalı bir gecede sustu. Parazit yok, cızırtı yok. Hiçbir şey yok.",
		"event.dead_channel.choice.0.text": "Sessizce yeniden kur.",
		"event.dead_channel.choice.0.note": "-10 Bütçe, +3 Operasyon İzi",
		"event.dead_channel.choice.1.text": "Açığa çıktığını varsay.",
		"event.dead_channel.choice.1.note": "-5 İstihbarat, +5 Gizlilik",
		"event.fractured_report.title": "Çelişkili Rapor",
		"event.fractured_report.desc": "Güvenilir iki analist aynı bölge için çelişkili değerlendirmeler sundu.",
		"event.fractured_report.choice.0.text": "Üçüncü bir inceleme yaptır.",
		"event.fractured_report.choice.0.note": "-6 Bütçe, +8 İstihbarat",
		"event.fractured_report.choice.1.text": "Bulguların ortalamasını al.",
		"event.fractured_report.choice.1.note": "Bir bölgede -İstikrar",
		"event.emergency_session.title": "Acil Oturum",
		"event.emergency_session.desc": "Komite gece toplandı. Küresel göstergeler sessiz bir eşiği aştı.",
		"event.emergency_session.choice.0.text": "Acil yetki iste.",
		"event.emergency_session.choice.0.note": "+20 Bütçe, -10 Güven",
		"event.emergency_session.choice.1.text": "Gerilimi azaltma planı sun.",
		"event.emergency_session.choice.1.note": "-6 Küresel Risk, -12 Bütçe",
		"event.shadow_ledger.title": "Gölge Defteri",
		"event.shadow_ledger.desc": "Ele geçirilen bir defter, yarım bildiğin bir şifreyle rakibin finansman zincirinin bir kısmını gösteriyor.",
		"event.shadow_ledger.choice.0.text": "Tam şifre çözme çalışması.",
		"event.shadow_ledger.choice.0.note": "-10 İstihbarat, +9 Rakip Ağ Deşifresi",
		"event.shadow_ledger.choice.1.text": "Parçaları müttefiklere sat.",
		"event.shadow_ledger.choice.1.note": "+18 Bütçe, +4 Rakip Yayılımı",
		"event.data_fog.title": "Veri Sisi",
		"event.data_fog.desc": "Birkaç koridorda sinyal kalitesi düştü. Her akış aniden daha belirsiz.",
		"event.data_fog.choice.0.text": "Temiz röleler için ödeme yap.",
		"event.data_fog.choice.0.note": "-12 Bütçe",
		"event.data_fog.choice.1.text": "Bozuk veriyle çalış.",
		"event.data_fog.choice.1.note": "-6 İstihbarat",
		"event.rumor_storm.title": "Yerel Söylenti Fırtınası",
		"event.rumor_storm.desc": "Yabancı gözlemciler hakkındaki uydurma bir hikâye bir bölgenin mahallelerine yayılıyor.",
		"event.rumor_storm.choice.0.text": "Gerçeklerle karşılık ver.",
		"event.rumor_storm.choice.0.note": "-8 Bütçe, bir bölgede -Kamuoyu Baskısı",
		"event.rumor_storm.choice.1.text": "Kendi kendine sönsün.",
		"event.rumor_storm.choice.1.note": "+Kamuoyu Baskısı, bir bölgede -İstikrar",
		"event.signal_contamination.title": "Sinyal Kirlenmesi",
		"event.signal_contamination.desc": "Dinleme arşivinde kasıtlı zehirleme izleri var. Haftalarca veri şüpheli.",
		"event.signal_contamination.choice.0.text": "Arşivi temizle.",
		"event.signal_contamination.choice.0.note": "-10 İstihbarat, +6 Gizlilik",
		"event.signal_contamination.choice.1.text": "İşaretle ve her şeyi sakla.",
		"event.signal_contamination.choice.1.note": "+5 Rakip Yayılımı",
		"event.friendly_audit.title": "Nezaket İncelemesi",
		"event.friendly_audit.desc": "Müttefik bir büro maruziyet durumunu incelemeyi teklif ediyor. Yardımları asla karşılıksız değil.",
		"event.friendly_audit.choice.0.text": "İncelemeyi kabul et.",
		"event.friendly_audit.choice.0.note": "-8 Küresel Risk, -6 İstihbarat",
		"event.friendly_audit.choice.1.text": "Nazikçe reddet.",
		"event.friendly_audit.choice.1.note": "+4 Gizlilik",
		"event.cold_pitch.title": "Soğuk Teklif",
		"event.cold_pitch.desc": "Bir yabancı ölü kutuya tek satırlık mesaj bıraktı: 'Üçünün adını verebilirim.'",
		"event.cold_pitch.choice.0.text": "Görüşmeye git.",
		"event.cold_pitch.choice.0.note": "+8 Rakip Ağ Deşifresi, +8 Operasyon İzi",
		"event.cold_pitch.choice.1.text": "Önce sınamadan geçir.",
		"event.cold_pitch.choice.1.note": "-5 İstihbarat, +4 Rakip Ağ Deşifresi",
		"event.cold_pitch.choice.2.text": "Ölü kutuyu imha et.",
		"event.cold_pitch.choice.2.note": "+5 Gizlilik",
		"event.budget_freeze.title": "Bütçe Dondurma",
		"event.budget_freeze.desc": "İlgisiz bir skandal incelenirken bürodaki ödemeler askıya alındı.",
		"event.budget_freeze.choice.0.text": "Eski iyilikleri tahsil et.",
		"event.budget_freeze.choice.0.note": "+15 Bütçe, -5 Güven",
		"event.budget_freeze.choice.1.text": "Dondurmayı sineye çek.",
		"event.budget_freeze.choice.1.note": "Bir ajana +Yorgunluk",
		"event.overheard_name.title": "Duyulan İsim",
		"event.overheard_name.desc": "Gizlilik kimliklerinden biri dinlenen bir konuşmada sesli söylendi.",
		"event.overheard_name.choice.0.text": "Kimliği emekliye ayır.",
		"event.overheard_name.choice.0.note": "-8 Gizlilik, -10 Operasyon İzi",
		"event.overheard_name.choice.1.text": "Yem olarak etkin tut.",
		"event.overheard_name.choice.1.note": "+6 Rakip Ağ Deşifresi, +6 Küresel Risk",
		"event.stability_grant.title": "İstikrar Hibesi",
		"event.stability_grant.desc": "Tarafsız bir kalkınma fonu bölgesel istikrar için eş finansman teklif ediyor.",
		"event.stability_grant.choice.0.text": "Hibeye eş finansman sağla.",
		"event.stability_grant.choice.0.note": "-15 Bütçe, her yerde +4 İstikrar",
		"event.stability_grant.choice.1.text": "Bağlantıyı reddet.",
		"event.stability_grant.choice.1.note": "Etkisi yok",
		"event.misfiled_dossier.title": "Yanlış Dosyalanmış Dosya",
		"event.misfiled_dossier.desc": "Hassas bir dosya altı gün yanlış arşivde kaldı. Birileri okumuş olabilir.",
		"event.misfiled_dossier.choice.0.text": "İç soruşturma başlat.",
		"event.misfiled_dossier.choice.0.note": "-8 Bütçe, +4 Güven",
		"event.misfiled_dossier.choice.1.text": "Yeniden sınıflandır ve devam et.",
		"event.misfiled_dossier.choice.1.note": "+5 Operasyon İzi",
		"event.rival_recruiter.title": "Rakip Toplayıcı",
		"event.rival_recruiter.desc": "Rakip ağ, temaslarının olduğu bir bölgede sessizce eleman topluyor.",
		"event.rival_recruiter.choice.0.text": "Daha yüksek teklif ver.",
		"event.rival_recruiter.choice.0.note": "-14 Bütçe, bir bölgede -Rakip Etkisi",
		"event.rival_recruiter.choice.1.text": "Kendi adamlarından birini sıraya sok.",
		"event.rival_recruiter.choice.1.note": "+6 Operasyon İzi, +7 Rakip Ağ Deşifresi",
		"event.quiet_quarter.title": "Sessiz Çeyrek",
		"event.quiet_quarter.desc": "Bir kez olsun hiçbir yer yanmıyor. Sessizlik neredeyse şüpheli.",
		"event.quiet_quarter.choice.0.text": "Kadroyu dinlendir.",
		"event.quiet_quarter.choice.0.note": "Tüm ajanlar Yorgunluk giderir",
		"event.quiet_quarter.choice.1.text": "Avantajı kullan.",
		"event.quiet_quarter.choice.1.note": "+6 İstihbarat, +4 Operasyon İzi",
		"event.border_incident.title": "Sınır Olayı",
		"event.border_incident.desc": "Bölgesel bir kontrol noktasındaki küçük çatışma daha büyük dikkat çekmek üzere.",
		"event.border_incident.choice.0.text": "Kanallar üzerinden arabuluculuk yap.",
		"event.border_incident.choice.0.note": "-10 Bütçe, bir bölgede +İstikrar",
		"event.border_incident.choice.1.text": "Belgele, müdahale etme.",
		"event.border_incident.choice.1.note": "+5 İstihbarat, bir bölgede -İstikrar",
		"event.encrypted_gift.title": "Şifreli Hediye",
		"event.encrypted_gift.desc": "Anonim bir pakette depolama aygıtı var. Ya hazine ya da tuzak.",
		"event.encrypted_gift.choice.0.text": "Yalıtılmış ortamda aç.",
		"event.encrypted_gift.choice.0.note": "+10 İstihbarat, +5 Operasyon İzi",
		"event.encrypted_gift.choice.1.text": "Açmadan imha et.",
		"event.encrypted_gift.choice.1.note": "+4 Gizlilik",
		"event.collapsed_echo.title": "Çöküşün Yankıları",
		"event.collapsed_echo.desc": "Çökmüş bir bölgenin düzensizliği komşularının piyasalarına ve sokaklarına taşıyor.",
		"event.collapsed_echo.choice.0.text": "Kontrol koridorlarını finanse et.",
		"event.collapsed_echo.choice.0.note": "-18 Bütçe, her yerde +3 İstikrar",
		"event.collapsed_echo.choice.1.text": "Yayılmayı kabullen.",
		"event.collapsed_echo.choice.1.note": "Her yerde -3 İstikrar",
		"event.old_alliance_call.title": "Eski Bir Mutabakat",
		"event.old_alliance_call.desc": "Daha dostane bir dönemden emekli bir muhatap özel tavsiye teklif ediyor.",
		"event.old_alliance_call.choice.0.text": "Buluş.",
		"event.old_alliance_call.choice.0.note": "+10 Güven, +3 Operasyon İzi",
		"event.old_alliance_call.choice.1.text": "Bazı kapılar kapalı kalmalı.",
		"event.old_alliance_call.choice.1.note": "Etkisi yok",
		"event.pattern_bleed.title": "Örüntü Sızıntısı",
		"event.pattern_bleed.desc": "Operasyon ritmin tahmin edilebilir hale geliyor. Birileri seni haritalıyor.",
		"event.pattern_bleed.choice.0.text": "Programları rastgeleleştir.",
		"event.pattern_bleed.choice.0.note": "Bir ajana +Yorgunluk, +8 Gizlilik",
		"event.pattern_bleed.choice.1.text": "Tempoyu koru.",
		"event.pattern_bleed.choice.1.note": "+4 Rakip Yayılımı",
		"event.press_leak_race.title": "Baskıya Yetişme Yarışı",
		"event.press_leak_race.desc": "Bir gazeteci yüzde sekseni doğru olan bir haber için görüş istiyor.",
		"event.press_leak_race.choice.0.text": "Gecikme karşılığında erişim ver.",
		"event.press_leak_race.choice.0.note": "-6 İstihbarat, -5 Küresel Risk",
		"event.press_leak_race.choice.1.text": "Yorum yok.",
		"event.press_leak_race.choice.1.note": "+7 Küresel Risk",
		"event.internal_doubt.title": "İç Şüphe",
		"event.internal_doubt.desc": "Üst düzey personel rakip ağın bu ölçekte var olup olmadığını sessizce sorguluyor.",
		"event.internal_doubt.choice.0.text": "Ham kanıtı paylaş.",
		"event.internal_doubt.choice.0.note": "-5 İstihbarat, +8 Güven",
		"event.internal_doubt.choice.1.text": "Disiplin talep et.",
		"event.internal_doubt.choice.1.note": "-4 Güven, bir ajana +Yorgunluk",
		"event.gray_donor.title": "Gri Bağışçı",
		"event.gray_donor.desc": "Özel bir hayırsever, kibarca dile getirilmeyen beklentilerle ciddi finansman teklif ediyor.",
		"event.gray_donor.choice.0.text": "Bütçeyi kabul et.",
		"event.gray_donor.choice.0.note": "+30 Bütçe, +8 Operasyon İzi, -5 Güven",
		"event.gray_donor.choice.1.text": "Reddet.",
		"event.gray_donor.choice.1.note": "+5 Güven",
		"event.night_signal.title": "Gece Sinyali",
		"event.night_signal.desc": "Sessiz sandığın bir bölgeden tek ve güçlü bir yayın yükseldi.",
		"event.night_signal.choice.0.text": "Hemen üçgenleme yap.",
		"event.night_signal.choice.0.note": "-8 Bütçe, bir bölgede rakip varlığını açığa çıkar",
		"event.night_signal.choice.1.text": "Kaydet ve bekle.",
		"event.night_signal.choice.1.note": "Bir bölgede +Rakip Etkisi",
	},
}
