extends Node
## LocalizationManager.gd - small UI localization helper.
## Static gameplay data remains in its source JSON for this pass.

signal locale_changed(locale: String)

const DEFAULT_LOCALE := "en"
const LANGUAGES: Array[Dictionary] = [
	{"code": "en", "label": "English"},
	{"code": "tr", "label": "Türkçe"},
]

const TEXT := {
	"en": {
		"brand.subtitle": "SILENT CARTOGRAPHY",
		"common.back": "BACK",
		"common.begin": "BEGIN",
		"common.close": "CLOSE",
		"common.continue": "CONTINUE",
		"common.main_menu": "MAIN MENU",
		"common.menu": "MENU",
		"common.none": "None",
		"common.roster": "ROSTER",
		"common.skip": "SKIP",
		"common.pass_turn": "PASS TURN",
		"menu.new_game": "NEW GAME",
		"menu.continue": "CONTINUE",
		"menu.how_to_play": "HOW TO PLAY",
		"menu.settings": "SETTINGS",
		"menu.exit": "EXIT",
		"menu.footer": "A fictional intelligence simulation. v1.0",
		"settings.title": "SETTINGS",
		"settings.music": "Music Volume",
		"settings.sfx": "SFX Volume",
		"settings.haptics": "Haptic Feedback",
		"settings.large_text": "Large Text",
		"settings.reduce_motion": "Reduce Motion",
		"settings.language": "Language",
		"settings.reset": "RESET SAVE DATA",
		"settings.reset_confirm": "TAP AGAIN TO CONFIRM RESET",
		"settings.reset_done": "SAVE DATA CLEARED",
		"settings.about_title": "ABOUT",
		"settings.about_body": "Fictional and abstract. No real countries, agencies, or persons are depicted. Built with Godot Engine.",
		"new_game.title": "SELECT POSTURE",
		"new_game.hint": "Choose how much the world will forgive.",
		"new_game.begin": "BEGIN %s",
		"difficulty.0.name": "Rookie Desk",
		"difficulty.0.desc": "Forgiving. More funds, slower exposure, gentler events.",
		"difficulty.1.name": "Standard Watch",
		"difficulty.1.desc": "The intended experience. Balanced pressure.",
		"difficulty.2.name": "Black Room",
		"difficulty.2.desc": "Unforgiving. Thin resources, fast rival spread, harsh failures.",
		"game.turn": "TURN",
		"game.intel": "INTEL",
		"game.funds": "FUNDS",
		"game.trust": "TRUST",
		"game.cover": "COVER",
		"game.heat": "HEAT",
		"game.rival_meter": "RIVAL NETWORK",
		"game.global_meter": "GLOBAL EXPOSURE",
		"game.stability": "Stability %d",
		"game.momentum": "Momentum %d",
		"game.objective": "Goal: expose Rival Network before Global Exposure reaches 100.",
		"game.danger": "Danger: Global %d/100 | Trust %d | Lost regions %d/%d",
		"game.step_region": "Step 1: Select a region",
		"game.step_region_detail": "Tap a region node to open its dossier.",
		"game.step_next_region_detail": "Tap a region node to begin the next operation.",
		"game.step_review_region": "Step 2: Review region",
		"game.step_review_region_detail": "Choose Agent to assign work here.",
		"game.step_agent": "Step 2: Choose an agent",
		"game.step_agent_detail": "Pick the agent whose skills fit the job.",
		"game.step_operation": "Step 3: Choose an operation",
		"game.step_operation_detail": "Check cost, chance, Heat, and expected effect.",
		"game.step_result": "Step 4: Review the result",
		"game.step_result_detail": "Read what changed, then adapt next turn.",
		"game.step_result_next_detail": "Read what changed, then choose the next region.",
		"game.step_pass_detail": "Agents rest while the rival network moves.",
		"game.incoming_report": "Incoming report",
		"game.incoming_report_detail": "Choose a response, then review the consequences.",
		"game.directive_title": "DIRECTIVE",
		"game.directive_body": "Expose the Rival Network before Global Exposure reaches 100. Select a region, assign an agent, then run an operation. Build local networks and use Trace Rival Cell to progress toward victory.",
		"game.no_consequence": "No measurable consequences. Yet.",
		"game.pass_debrief_title": "Holding Pattern - agents rest",
		"game.verdict_success": "SUCCESS",
		"game.verdict_near_miss": "NEAR MISS",
		"game.verdict_failure": "FAILURE",
		"game.result_title": "%s - %s (%d%% chance, roll %d)",
		"region.classification": "Classification: %s",
		"region.unknown": "UNKNOWN",
		"region.intel_level": "Intel Level %d/3",
		"region.collapsed": "REGION COLLAPSED. No further operations possible here.",
		"region.stability": "Stability",
		"region.rival": "Rival Influence",
		"region.surveillance": "Surveillance",
		"region.pressure": "Public Pressure",
		"region.network": "Local Network",
		"region.opportunity": "Opportunity",
		"region.need_intel": "Need Intel",
		"region.map_signals_hint": "Run Map Signals here to reveal more.",
		"region.choose_agent": "CHOOSE AGENT",
		"agent.title": "AGENT ROSTER",
		"agent.select_title": "SELECT AGENT",
		"agent.roster_hint": "Review fatigue, traits, and skill coverage.",
		"agent.select_hint": "Choose one agent for the next operation.",
		"agent.level_short": "LV %d",
		"agent.trait": "Trait: %s",
		"agent.fatigue_status": "Fatigue %d / %s",
		"agent.ready": "Ready",
		"agent.strained": "Strained",
		"agent.select": "SELECT AGENT",
		"operation.title": "SELECT OPERATION",
		"operation.choose": "CHOOSE AN OPERATION",
		"operation.chance": "Chance %d%%",
		"operation.cost": "Cost",
		"operation.heat": "Heat",
		"operation.effect": "Effect",
		"operation.insufficient": "Insufficient resources.",
		"operation.run": "RUN OPERATION",
		"debrief.title": "OPERATION DEBRIEF",
		"debrief.global": "GLOBAL",
		"debrief.rival": "RIVAL",
		"debrief.heat": "HEAT",
		"debrief.funds": "FUNDS",
		"debrief.more": "%d additional changes recorded.",
		"event.strip": "INCOMING REPORT / %s",
		"tone.pressure": "PRESSURE",
		"tone.internal": "INTERNAL",
		"tone.rival": "RIVAL",
		"tone.world": "WORLD",
		"tone.opportunity": "OPPORTUNITY",
		"win.title": "NETWORK EXPOSED",
		"win.fallback": "Victory.",
		"loss.title": "DIRECTORATE DOWN",
		"loss.fallback": "The campaign has ended.",
		"end.reason.win": "The rival network has been fully exposed. Its structure is public, its cover gone.",
		"end.reason.global": "Global Exposure reached the point of no return. The crisis is now irreversible.",
		"end.reason.trust": "Agency Trust collapsed. The Directorate has been dissolved by emergency decree.",
		"end.reason.collapse": "Five regions have collapsed. The map you were protecting no longer exists.",
		"end.reason.funds": "The Directorate is insolvent. Operations ceased; the rival moves unopposed.",
		"end.turns": "Turns survived: %d",
		"end.ops": "Operations run: %d (%d successful)",
		"end.events": "Events faced: %d",
		"end.regions": "Regions lost: %d",
		"end.rival": "Rival network exposed: %d%%",
		"end.posture": "Posture: %s",
		"end.new_campaign": "NEW CAMPAIGN",
		"end.try_again": "TRY AGAIN",
		"tutorial.region": "Welcome, Director. Tap any region node on the map to open its dossier.",
		"tutorial.region_read": "This is the region dossier. Stability, Rival Influence and Surveillance decide how risky work here will be. Tap CHOOSE AGENT.",
		"tutorial.roster": "Every operation needs an agent. This is your roster.",
		"tutorial.agent": "Each agent is better at some work than others. Select any agent to continue.",
		"tutorial.map_signals": "Operations show cost, odds and Heat before you commit. Choose MAP SIGNALS - the safest way to learn a region.",
		"tutorial.resolve": "Run the operation and read the debrief.",
		"tutorial.intel": "INTEL is your analytical currency. Spend it on Deep Analysis and predictions. Earn it by mapping signals. (Tap to continue)",
		"tutorial.heat": "HEAT is how visible you are. High Heat feeds Global Exposure and triggers hostile events. Cool it down before it burns you. (Tap to continue)",
		"tutorial.rival": "RIVAL NETWORK EXPOSURE is your victory meter. Build local networks, then run Trace Rival Cell to push it to 100. (Tap to continue)",
		"tutorial.finish": "The rest is judgment. Watch the map, spend carefully, and expose them before the world unravels. Good luck, Director. (Tap to finish)",
		"how.title": "HOW TO PLAY",
		"how.mission.title": "Mission",
		"how.mission.body": "Expose the Rival Network before Global Exposure reaches 100.",
		"how.mission.losses": "Failure comes from Global Exposure at 100, Agency Trust at 0, or too many collapsed regions.",
		"how.flow.title": "Turn Flow",
		"how.flow.1": "Select a region",
		"how.flow.2": "Choose an agent",
		"how.flow.3": "Choose an operation",
		"how.flow.4": "Review the result",
		"how.flow.5": "Respond to events",
		"how.flow.6": "Repeat",
		"how.resources.title": "Resources",
		"how.res.intel": "Used for analysis and some operations. Earn it by mapping signals.",
		"how.res.funds": "Pays operation costs and agent upkeep.",
		"how.res.trust": "Your mandate. If Trust reaches 0, the run ends.",
		"how.res.cover": "Absorbs fallout when operations go badly.",
		"how.res.heat": "Your visibility. High Heat accelerates Global Exposure.",
		"how.global.title": "Global Situation",
		"how.global.rival": "Victory meter. Push Rival Network Exposure to 100.",
		"how.global.exposure": "Loss meter. If Global Exposure reaches 100, the crisis wins.",
		"how.global.stability_label": "STABILITY",
		"how.global.momentum_label": "MOMENTUM",
		"how.global.stability": "Average regional stability. Low stability means collapse risk.",
		"how.global.momentum": "How fast the rival network spreads pressure.",
		"how.first.title": "First Moves",
		"how.first.1": "Tap a region and read its dossier.",
		"how.first.2": "Assign an agent whose skills fit the operation.",
		"how.first.3": "Use Map Signals or Build Local Network early.",
		"how.first.4": "Use Trace Rival Cell when odds are favorable.",
		"how.tips.title": "Operational Tips",
		"how.tip.1": "High Heat increases danger.",
		"how.tip.2": "Stable regions are easier to manage.",
		"how.tip.3": "Local networks improve future operations.",
		"how.tip.4": "Do not ignore rising global pressure.",
		"how.intelligence.title": "Region Intelligence",
		"how.intelligence.map": "Map Signals raises intelligence coverage and reveals regional metrics.",
		"how.intelligence.analysis": "Deep Analysis reveals the region's hidden identity.",
		"how.intelligence.identity": "A revealed identity changes only the operations it supports.",
		"difficulty.0.short": "Rookie",
		"difficulty.1.short": "Standard",
		"difficulty.2.short": "Black Room",
		"game.funds_short": "F",
		"game.intel_short": "I",
		"game.trust_short": "T",
		"game.difficulty": "POSTURE",
		"game.lost": "LOST",
		"game.world_stability": "STABILITY",
		"game.rival_momentum": "MOMENTUM",
		"game.outlook": "OUTLOOK",
		"game.legend": "LEGEND",
		"hud.risks_nominal": "Loss risks: Global 100 / Trust 0 / %d collapsed regions.",
		"hud.warning.global": "Critical: Global Exposure is %d/100.",
		"hud.warning.trust": "Critical: Agency Trust is down to %d.",
		"hud.warning.funds": "Critical: Funds are overdrawn at %d.",
		"hud.warning.heat": "Warning: Heat is elevated at %d.",
		"hud.warning.heat_danger": "Critical: Heat is at %d and feeding exposure.",
		"hud.warning.collapsed": "Critical: %d/%d regions have collapsed.",
		"hud.warning.momentum": "Warning: Rival Momentum has reached %d.",
		"outlook.title": "TURN OUTLOOK",
		"outlook.economy": "Expected Economy",
		"outlook.base_income": "Base income",
		"outlook.trust_income": "Trust contribution",
		"outlook.agent_upkeep": "Agent upkeep",
		"outlook.trade_hubs": "Revealed Trade Hubs",
		"outlook.budget_change": "Expected budget change",
		"outlook.pressure": "Passive Pressure",
		"outlook.heat_change": "Passive Heat change",
		"outlook.exposure_pressure": "Exposure pressure",
		"outlook.approx": "about +%.1f",
		"outlook.rival_activity": "Rival activity",
		"outlook.activity.low": "Low",
		"outlook.activity.moderate": "Moderate",
		"outlook.activity.high": "High",
		"outlook.disclaimer": "Expected passive effects only. Random events and rival targets are not predicted.",
		"legend.title": "MAP LEGEND",
		"legend.risk.title": "Risk ring",
		"legend.risk.body": "Amber and red borders mark known instability or rival pressure; an alert mark signals urgency.",
		"legend.opportunity.title": "Opportunity halo",
		"legend.opportunity.body": "A soft green halo marks strong Opportunity after that metric is known.",
		"legend.intel.title": "Intel pips",
		"legend.intel.body": "The three pips below a node show current intelligence coverage.",
		"legend.selected.title": "Selected region",
		"legend.selected.body": "A cyan outer ring marks the dossier currently in focus.",
		"legend.collapsed.title": "Collapsed region",
		"legend.collapsed.body": "Muted, fractured nodes can no longer receive operations.",
		"legend.identity.title": "Known identity",
		"legend.identity.body": "A small diamond appears only after the regional identity is revealed.",
		"map.lost_short": "LOST",
		"assessment.critical": "Critical",
		"assessment.unstable": "Unstable",
		"assessment.contested": "Contested",
		"assessment.promising": "Promising",
		"assessment.under_observed": "Under-observed",
		"assessment.stable": "Stable",
		"region.classified": "CLASSIFIED",
		"region.intel_short": "Intel %d/3",
		"region.requires_intel": "Requires Intel Level %d",
		"region.plan_operation": "PLAN OPERATION",
		"region.section.situation": "Immediate Situation",
		"region.section.metrics": "Known Regional Metrics",
		"region.section.gaps": "Intelligence Gaps",
		"region.section.identity": "Active Regional Identity",
		"region.section.recommendations": "Strategic Options",
		"region.gap.level1": "Map Signals reveals Rival Influence and Surveillance.",
		"region.gap.level2": "Map Signals reveals Public Pressure and Opportunity.",
		"region.gap.level3": "One more intelligence pass completes regional coverage.",
		"region.gap.identity": "Deep Analysis reveals the regional identity and its operation modifiers.",
		"region.summary.unavailable": "No reliable situation report is available.",
		"region.summary.collapsed": "The region has collapsed and no longer supports operations.",
		"region.summary.low_stability_limited": "Stability is deteriorating, while intelligence coverage remains limited.",
		"region.summary.limited": "The region appears manageable, but intelligence coverage remains limited.",
		"region.summary.rival_deteriorating": "Rival activity is high and regional stability is deteriorating.",
		"region.summary.surveillance": "The region is holding, but surveillance makes covert work difficult.",
		"region.summary.pressure": "Public pressure is rising and may undermine regional stability.",
		"region.summary.opportunity": "Local opportunity is strong enough to support focused operations.",
		"region.summary.stable": "Known indicators are stable with no immediate regional crisis.",
		"advisor.none": "No urgent recommendation. Review the full operation set before committing.",
		"advisor.map_signals": "Improve intelligence coverage before relying on incomplete regional data.",
		"advisor.stabilize": "Restore Stability before the region approaches collapse.",
		"advisor.reduce_heat": "Reduce Heat before another visible operation compounds exposure.",
		"advisor.counter_influence": "Counter Influence while the rival foothold is clearly visible.",
		"advisor.deep_analysis": "Reveal the regional identity to unlock its strategic advantage.",
		"advisor.build_network": "Build Local Network to improve future odds in this region.",
		"advisor.trace_cell": "Network support is strong enough to consider tracing the rival cell.",
		"advisor.identity.trade_hub": "Use the region deliberately while its revealed identity supports the wider budget.",
		"advisor.identity.media_core": "Reduce Heat here to exploit the Media Core advantage.",
		"advisor.identity.border_zone": "Counter Influence or contain a crisis while the Border Zone amplifies impact.",
		"advisor.identity.research_node": "Map Signals here for a stronger intelligence return.",
		"advisor.identity.financial_gate": "Use expensive operations here while Funds costs are reduced.",
		"advisor.identity.civil_pressure_zone": "Stabilize here to gain the full civil-pressure advantage.",
		"advisor.identity.signal_corridor": "Trace Rival Cell here when network support and odds align.",
		"advisor.identity.old_alliance": "Quiet Audit can convert this identity into additional Trust.",
		"advisor.identity.black_market_route": "Build Local Network here when the extra Heat is acceptable.",
		"advisor.identity.diplomatic_junction": "Diplomacy operations gain the clearest advantage here.",
		"region_tag.trade_hub.name": "Trade Hub",
		"region_tag.trade_hub.description": "Each revealed, active Trade Hub adds +2 Funds during turn income, up to +6 total.",
		"region_tag.media_core.name": "Media Core",
		"region_tag.media_core.description": "Reduce Heat removes 25% more Heat in this region.",
		"region_tag.border_zone.name": "Border Zone",
		"region_tag.border_zone.description": "Counter Influence and Emergency Containment effects are 15% stronger here.",
		"region_tag.research_node.name": "Research Node",
		"region_tag.research_node.description": "Map Signals grants 25% more Intel; Deep Analysis costs 2 less Intel.",
		"region_tag.financial_gate.name": "Financial Gate",
		"region_tag.financial_gate.description": "Funds costs for operations in this region are reduced by 15%.",
		"region_tag.civil_pressure_zone.name": "Civil Pressure Zone",
		"region_tag.civil_pressure_zone.description": "Stabilize restores 20% more Stability and reduces 15% more Public Pressure.",
		"region_tag.signal_corridor.name": "Signal Corridor",
		"region_tag.signal_corridor.description": "Trace Rival Cell gains +8 chance; Map Signals gains +4 chance.",
		"region_tag.old_alliance.name": "Old Alliance",
		"region_tag.old_alliance.description": "Quiet Audit restores 25% more Trust; Stabilize gains +4 chance.",
		"region_tag.black_market_route.name": "Black Market Route",
		"region_tag.black_market_route.description": "Build Local Network is 25% stronger but generates +2 additional Heat.",
		"region_tag.diplomatic_junction.name": "Diplomatic Junction",
		"region_tag.diplomatic_junction.description": "Diplomacy operations gain +6 chance; Quiet Audit costs 2 fewer Funds.",
		"region_tag.modifier.trade_hub.income": "Revealed Trade Hubs added +%d Funds during the budget cycle.",
		"region_tag.modifier.media_core.reduce_heat": "Media Core strengthens Heat reduction by 25%.",
		"region_tag.modifier.border_zone.operation": "Border Zone strengthens this operation's effect by 15%.",
		"region_tag.modifier.research_node.map": "Research Node increases the Intel gained by 25%.",
		"region_tag.modifier.research_node.analysis": "Research Node reduces Deep Analysis Intel cost by 2.",
		"region_tag.modifier.financial_gate.operation": "Financial Gate reduces the Funds cost by 15%.",
		"region_tag.modifier.civil_pressure.stabilize": "Civil Pressure Zone strengthens both Stability and pressure relief.",
		"region_tag.modifier.signal_corridor.trace": "Signal Corridor adds +8 to Trace Rival Cell chance.",
		"region_tag.modifier.signal_corridor.map": "Signal Corridor adds +4 to Map Signals chance.",
		"region_tag.modifier.old_alliance.audit": "Old Alliance increases Trust restored by 25%.",
		"region_tag.modifier.old_alliance.stabilize": "Old Alliance adds +4 to Stabilize chance.",
		"region_tag.modifier.black_market.network": "Black Market Route strengthens network growth by 25%.",
		"region_tag.modifier.black_market.heat": "Black Market Route adds +2 Heat to this operation.",
		"region_tag.modifier.diplomatic.operation": "Diplomatic Junction adds +6 chance to diplomacy work and discounts Quiet Audit.",
		"region_tag.discovery_reward": "First identity discovery granted +%d Intel.",
		"skill.analysis": "Analysis",
		"skill.fieldcraft": "Fieldcraft",
		"skill.diplomacy": "Diplomacy",
		"skill.technical": "Technical",
		"skill.resolve": "Resolve",
		"skill.analysis.short": "ANL",
		"skill.fieldcraft.short": "FLD",
		"skill.diplomacy.short": "DIP",
		"skill.technical.short": "TEC",
		"skill.resolve.short": "RSV",
		"agent_role.analyst": "Analyst",
		"agent_role.field_observer": "Field Observer",
		"agent_role.liaison": "Liaison",
		"agent_role.signal_specialist": "Signal Specialist",
		"agent_role.crisis_negotiator": "Crisis Negotiator",
		"agent_role.network_handler": "Network Handler",
		"agent.strengths": "Strengths: %s",
		"agent.fit.strong": "Strong fit",
		"agent.fit.viable": "Viable",
		"agent.fit.risky": "Risky",
		"agent.fit.exhausted": "Exhausted",
		"agent.fit.specialist": "Specialist advantage",
		"agent.fit.tradeoff": "Trait tradeoff",
		"agent.fit.best": "Best current option: %s at %d%%",
		"agent_trait.fast_analyst.name": "Fast Analyst",
		"agent_trait.fast_analyst.description": "Map Signals produces more Intel.",
		"agent_trait.low_profile.name": "Low Profile",
		"agent_trait.low_profile.description": "Operations generate less Heat.",
		"agent_trait.risk_averse.name": "Risk Averse",
		"agent_trait.risk_averse.description": "Safer odds, but weaker successful effects.",
		"agent_trait.expensive_specialist.name": "Expensive Specialist",
		"agent_trait.expensive_specialist.description": "Better odds at a higher Funds cost.",
		"agent_trait.calm_under_pressure.name": "Calm Under Pressure",
		"agent_trait.calm_under_pressure.description": "Failure penalties are reduced.",
		"agent_trait.unstable_contact.name": "Unstable Contact",
		"agent_trait.unstable_contact.description": "Stronger effects with greater event risk.",
		"agent_trait.modifier.expensive.chance": "Expensive Specialist improves success chance.",
		"agent_trait.modifier.expensive.cost": "Expensive Specialist increases Funds cost.",
		"agent_trait.modifier.risk_averse.chance": "Risk Averse improves success chance.",
		"agent_trait.modifier.risk_averse.effect": "Risk Averse reduces successful effect strength.",
		"agent_trait.modifier.low_profile.heat": "Low Profile reduces generated Heat.",
		"agent_trait.modifier.fast_analyst.intel": "Fast Analyst increases Intel gained from Map Signals.",
		"agent_trait.modifier.calm.failure": "Calm Under Pressure reduces failure fallout.",
		"agent_trait.modifier.unstable.effect": "Unstable Contact strengthens successful effects.",
		"agent_trait.modifier.unstable.event": "Unstable Contact increased this turn's event risk.",
		"operation.map_signals.name": "Map Signals",
		"operation.map_signals.description": "Sweep open channels to raise Intel Level and gain Intel.",
		"operation.map_signals.effect": "+1 Intel Level and +Intel",
		"operation.build_network.name": "Build Local Network",
		"operation.build_network.description": "Recruit quiet contacts to support future work in this region.",
		"operation.build_network.effect": "+Local Network",
		"operation.counter_influence.name": "Counter Influence",
		"operation.counter_influence.description": "Disrupt the rival foothold while accepting a visible footprint.",
		"operation.counter_influence.effect": "-Rival Influence",
		"operation.stabilize.name": "Stabilize Region",
		"operation.stabilize.description": "Coordinate local institutions to restore Stability and ease pressure.",
		"operation.stabilize.effect": "+Stability and -Public Pressure",
		"operation.reduce_heat.name": "Reduce Heat",
		"operation.reduce_heat.description": "Scrub operational trails and rebuild Directorate Cover.",
		"operation.reduce_heat.effect": "-Heat and +Cover",
		"operation.trace_cell.name": "Trace Rival Cell",
		"operation.trace_cell.description": "Follow rival threads toward their source. This is the main victory route.",
		"operation.trace_cell.effect": "+Rival Network Exposure",
		"operation.containment.name": "Emergency Containment",
		"operation.containment.description": "Commit heavy resources to hold a failing region quickly.",
		"operation.containment.effect": "Large +Stability and -Rival Influence",
		"operation.deep_analysis.name": "Deep Analysis",
		"operation.deep_analysis.description": "Cross-reference the dossier to reveal regional identity and complete coverage.",
		"operation.deep_analysis.effect": "Reveal identity and set Intel Level to maximum",
		"operation.quiet_audit.name": "Quiet Audit",
		"operation.quiet_audit.description": "Restore internal confidence and calm public pressure.",
		"operation.quiet_audit.effect": "+Trust and -Public Pressure",
		"operation.context.region": "%s / %s",
		"operation.context.agent": "%s / Fatigue %d",
		"operation.required_skill": "Required skill",
		"operation.skill_value": "%s %d",
		"operation.chance_label": "CHANCE",
		"operation.modifier.identity": "Identity",
		"operation.modifier.agent": "Agent trait",
		"operation.risk.favorable": "Favorable",
		"operation.risk.uncertain": "Uncertain",
		"operation.risk.risky": "Risky",
		"operation.risk.severe": "Severe risk",
		"operation.warning.resources": "Insufficient Funds or Intel prevents confirmation.",
		"operation.warning.fatigue": "High Fatigue is reducing this agent's real success chance.",
		"operation.warning.low_network": "Low Local Network limits the value and odds of tracing the cell.",
		"operation.warning.surveillance": "Known Surveillance makes this covert operation harder.",
		"operation.warning.low_trust": "The Trust cost is dangerous at the current mandate level.",
		"operation.warning.high_heat": "Current Heat is already increasing long-term exposure pressure.",
		"operation.confirm.low_chance": "Final success chance is unusually low.",
		"operation.confirm.high_heat": "This action would push Heat into a critical range.",
		"operation.confirm.low_trust": "This action would leave Trust close to collapse.",
		"operation.confirm.negative_funds": "This action would overdraw available Funds.",
		"operation.confirm_risk": "CONFIRM RISK",
		"operation.unavailable": "Unavailable: actual resource or region rules prevent confirmation.",
		"operation.unavailable_short": "UNAVAILABLE",
		"operation.breakdown.title": "Calculation Details",
		"operation.breakdown.chance": "Success Chance",
		"operation.breakdown.funds": "Funds Cost",
		"operation.breakdown.intel": "Intel Cost",
		"operation.breakdown.trust": "Trust Cost",
		"operation.breakdown.heat": "Generated Heat",
		"breakdown.base": "Base",
		"breakdown.agent_skill": "Agent skill",
		"breakdown.fatigue": "Fatigue",
		"breakdown.local_network": "Local Network",
		"breakdown.intel_level": "Intel Level",
		"breakdown.surveillance": "Surveillance",
		"breakdown.rival_influence": "Rival Influence",
		"breakdown.difficulty": "Posture",
		"breakdown.agent_trait": "Agent trait",
		"breakdown.region_identity": "Region identity",
		"breakdown.final": "Final",
		"debrief.operation_context": "%s / %s / %s",
		"debrief.chance_roll": "Final chance %d%% / Roll %d",
		"debrief.section.effects": "Immediate Effects",
		"debrief.section.modifiers": "Applied Modifiers",
		"debrief.section.identity": "Identity Revealed",
		"debrief.section.economy": "Turn Economy",
		"debrief.section.world": "Rival and World Response",
		"debrief.section.changes": "Changed Campaign State",
		"debrief.identity_delta.chance": "Regional identity changed final chance by %s.",
		"debrief.identity_delta.cost": "Regional identity changed %s cost by %s.",
		"debrief.identity_delta.heat": "Regional identity changed generated Heat by %s.",
		"debrief.identity_delta.effect": "Regional identity changed the %s effect by %s.",
		"debrief.metric.funds": "Funds",
		"debrief.metric.intel": "Intel",
		"debrief.metric.trust": "Trust",
		"debrief.metric.heat": "Heat",
		"debrief.metric.cover": "Cover",
		"debrief.metric.rival_exposure": "Rival Network Exposure",
		"debrief.metric.global_exposure": "Global Exposure",
		"debrief.metric.region_stability": "Region Stability",
		"debrief.metric.region_rival": "Region Rival Influence",
		"debrief.metric.region_pressure": "Region Public Pressure",
		"debrief.metric.local_network": "Local Network",
		"debrief.metric.intel_level": "Intel Level",
		"debrief.metric.rival_momentum": "Rival Momentum",
		"debrief.metric.world_stability": "World Stability",
		"debrief.metric.collapsed_regions": "Collapsed Regions",
		"debrief.metric.stability": "Stability",
		"debrief.metric.rival_influence": "Rival Influence",
		"debrief.metric.public_pressure": "Public Pressure",
		"resolve.trust_spent": "Committee approval spent: -%d Trust.",
		"resolve.heat_gain": "Operational footprint: +%d Heat.",
		"resolve.near_miss": "The operation fell short, but usable fragments were recovered.",
		"resolve.identity_revealed": "%s identified as %s. First discovery reward: +%d Intel.",
		"resolve.event_identity_revealed": "%s identified as %s.",
		"resolve.map_signals": "%s charted: Intel Level %d, +%d Intel.",
		"resolve.build_network": "Local Network in %s grew by %d, now %d.",
		"resolve.counter_influence": "Rival Influence in %s fell by %d.",
		"resolve.stabilize": "%s stabilized: +%d Stability, -%d Public Pressure.",
		"resolve.reduce_heat": "Trails scrubbed: -%d Heat, +%d Cover.",
		"resolve.trace_cell": "Cell traced through %s: +%d Rival Network Exposure.",
		"resolve.containment": "%s contained: +%d Stability, -%d Rival Influence.",
		"resolve.deep_analysis": "%s profile complete. Identity: %s.",
		"resolve.quiet_audit": "Audit filed: +%d Trust; Public Pressure eased in %s.",
		"resolve.cover_absorb": "Cover assets absorbed part of the fallout: -%d Cover.",
		"resolve.failure": "Failure fallout: +%d Heat, -%d Trust, %s Stability -%d.",
		"resolve.surveillance_tightened": "Local Surveillance tightened in %s.",
		"resolve.level_up": "%s reached Level %d; %s improved.",
		"resolve.budget_cycle": "Budget cycle: +%d income, -%d upkeep.",
		"resolve.trade_hub_income": "Revealed Trade Hubs contributed +%d Funds.",
		"resolve.passive_heat": "Passive cleanup reduced Heat by %d.",
		"resolve.exposure_pressure": "Passive pressure added about %.1f Global Exposure.",
		"resolve.overdrawn": "WARNING: The Directorate is overdrawn. Restore Funds this turn.",
		"resolve.rival_spread": "Rival signals strengthened in: %s.",
		"resolve.region_collapsed": "REGION COLLAPSED: %s has fallen into disorder.",
		"tutorial.intel_identity": "Map Signals raises intelligence coverage. Deep Analysis reveals a region's identity; revealed identities change suitable operations. (Tap to continue)",
		"tutorial.heat_network": "Agent skill and Fatigue change real odds. Local Network supports future work, while Heat feeds long-term danger. (Tap to continue)",
		"tutorial.identity_revealed": "Identity confirmed. Every identity changes different operations; read the dossier effect before planning here again. (Tap to return)",
	},
	"tr": {
		"brand.subtitle": "SESSİZ HARİTACILIK",
		"common.back": "GERİ",
		"common.begin": "BAŞLA",
		"common.close": "KAPAT",
		"common.continue": "DEVAM",
		"common.main_menu": "ANA MENÜ",
		"common.menu": "MENÜ",
		"common.none": "Yok",
		"common.roster": "KADRO",
		"common.skip": "GEÇ",
		"common.pass_turn": "TURU GEÇ",
		"menu.new_game": "YENİ OYUN",
		"menu.continue": "DEVAM ET",
		"menu.how_to_play": "NASIL OYNANIR",
		"menu.settings": "AYARLAR",
		"menu.exit": "ÇIKIŞ",
		"menu.footer": "Kurgusal istihbarat simülasyonu. v1.0",
		"settings.title": "AYARLAR",
		"settings.music": "Müzik Ses Düzeyi",
		"settings.sfx": "Efekt Ses Düzeyi",
		"settings.haptics": "Titreşim Geri Bildirimi",
		"settings.large_text": "Büyük Yazı",
		"settings.reduce_motion": "Hareketi Azalt",
		"settings.language": "Dil",
		"settings.reset": "KAYIT VERİSİNİ SIFIRLA",
		"settings.reset_confirm": "SIFIRLAMAK İÇİN TEKRAR DOKUN",
		"settings.reset_done": "KAYIT VERİSİ TEMİZLENDİ",
		"settings.about_title": "HAKKINDA",
		"settings.about_body": "Tamamen kurgusal ve soyuttur. Gerçek ülkeler, kurumlar veya kişiler tasvir edilmez. Godot Engine ile yapılmıştır.",
		"new_game.title": "DURUŞ SEÇ",
		"new_game.hint": "Dünyanın hatalara ne kadar tolerans göstereceğini seç.",
		"new_game.begin": "%s BAŞLAT",
		"difficulty.0.name": "Acemi Masa",
		"difficulty.0.desc": "Daha hoşgörülü. Daha fazla fon, daha yavaş iz, daha yumuşak olaylar.",
		"difficulty.1.name": "Standart Nöbet",
		"difficulty.1.desc": "Önerilen deneyim. Dengeli baskı.",
		"difficulty.2.name": "Kara Oda",
		"difficulty.2.desc": "Acımasız. Az kaynak, hızlı rakip yayılımı, sert hatalar.",
		"game.turn": "TUR",
		"game.intel": "İST",
		"game.funds": "FON",
		"game.trust": "GÜVEN",
		"game.cover": "ÖRTÜ",
		"game.heat": "ISI",
		"game.rival_meter": "RAKİP AĞ",
		"game.global_meter": "KÜRESEL İZ",
		"game.stability": "İstikrar %d",
		"game.momentum": "İvme %d",
		"game.objective": "Hedef: Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar.",
		"game.danger": "Tehlike: Küresel %d/100 | Güven %d | Kayıp bölge %d/%d",
		"game.step_region": "Adım 1: Bölge seç",
		"game.step_region_detail": "Dosyasını açmak için haritadaki bir bölgeye dokun.",
		"game.step_next_region_detail": "Sonraki operasyon için bir bölgeye dokun.",
		"game.step_review_region": "Adım 2: Bölgeyi incele",
		"game.step_review_region_detail": "Burada çalışacak ajanı seç.",
		"game.step_agent": "Adım 2: Ajan seç",
		"game.step_agent_detail": "İş için uygun becerilere sahip ajanı seç.",
		"game.step_operation": "Adım 3: Operasyon seç",
		"game.step_operation_detail": "Maliyet, şans, Isı ve beklenen etkiyi kontrol et.",
		"game.step_result": "Adım 4: Sonucu incele",
		"game.step_result_detail": "Neyin değiştiğini oku, sonraki tura uyum sağla.",
		"game.step_result_next_detail": "Neyin değiştiğini oku, sonra yeni bölge seç.",
		"game.step_pass_detail": "Ajanlar dinlenirken rakip ağ hareket eder.",
		"game.incoming_report": "Gelen rapor",
		"game.incoming_report_detail": "Bir yanıt seç, sonra sonuçları incele.",
		"game.directive_title": "DİREKTİF",
		"game.directive_body": "Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar. Bir bölge seç, ajan ata ve operasyon yürüt. Zafer için yerel ağlar kur, sonra Rakip Hücreyi İzle operasyonunu kullan.",
		"game.no_consequence": "Ölçülebilir bir sonuç yok. Şimdilik.",
		"game.pass_debrief_title": "Bekleme Durumu - ajanlar dinleniyor",
		"game.verdict_success": "BAŞARILI",
		"game.verdict_near_miss": "KIL PAYI",
		"game.verdict_failure": "BAŞARISIZ",
		"game.result_title": "%s - %s (%d%% şans, zar %d)",
		"region.classification": "Sınıflandırma: %s",
		"region.unknown": "BİLİNMİYOR",
		"region.intel_level": "İstihbarat Seviyesi %d/3",
		"region.collapsed": "BÖLGE ÇÖKTÜ. Burada artık operasyon yapılamaz.",
		"region.stability": "İstikrar",
		"region.rival": "Rakip Etkisi",
		"region.surveillance": "Gözetim",
		"region.pressure": "Kamu Baskısı",
		"region.network": "Yerel Ağ",
		"region.opportunity": "Fırsat",
		"region.need_intel": "İstihbarat gerekli",
		"region.map_signals_hint": "Daha fazlasını açmak için burada Sinyalleri Haritala.",
		"region.choose_agent": "AJAN SEÇ",
		"agent.title": "AJAN KADROSU",
		"agent.select_title": "AJAN SEÇ",
		"agent.roster_hint": "Yorgunluk, özellik ve beceri dağılımını incele.",
		"agent.select_hint": "Sonraki operasyon için bir ajan seç.",
		"agent.level_short": "SV %d",
		"agent.trait": "Özellik: %s",
		"agent.fatigue_status": "Yorgunluk %d / %s",
		"agent.ready": "Hazır",
		"agent.strained": "Zorlanmış",
		"agent.select": "AJAN SEÇ",
		"operation.title": "OPERASYON SEÇ",
		"operation.choose": "BİR OPERASYON SEÇ",
		"operation.chance": "Şans %d%%",
		"operation.cost": "Maliyet",
		"operation.heat": "Isı",
		"operation.effect": "Etki",
		"operation.insufficient": "Kaynaklar yetersiz.",
		"operation.run": "OPERASYONU YÜRÜT",
		"debrief.title": "OPERASYON RAPORU",
		"debrief.global": "KÜRESEL",
		"debrief.rival": "RAKİP",
		"debrief.heat": "ISI",
		"debrief.funds": "FON",
		"debrief.more": "%d ek değişiklik kaydedildi.",
		"event.strip": "GELEN RAPOR / %s",
		"tone.pressure": "BASKI",
		"tone.internal": "İÇ",
		"tone.rival": "RAKİP",
		"tone.world": "DÜNYA",
		"tone.opportunity": "FIRSAT",
		"win.title": "AĞ AÇIĞA ÇIKTI",
		"win.fallback": "Zafer.",
		"loss.title": "DİREKTÖRLÜK DÜŞTÜ",
		"loss.fallback": "Sefer sona erdi.",
		"end.reason.win": "Rakip ağ tamamen açığa çıkarıldı. Yapısı görünür, örtüsü yok oldu.",
		"end.reason.global": "Küresel İz geri dönüşsüz noktaya ulaştı. Kriz artık durdurulamaz.",
		"end.reason.trust": "Kurum Güveni çöktü. Direktörlük acil kararnameyle dağıtıldı.",
		"end.reason.collapse": "Beş bölge çöktü. Korumaya çalıştığın harita artık yok.",
		"end.reason.funds": "Direktörlük ödeme gücünü yitirdi. Operasyonlar durdu; rakip karşılıksız ilerliyor.",
		"end.turns": "Hayatta kalınan tur: %d",
		"end.ops": "Yürütülen operasyon: %d (%d başarılı)",
		"end.events": "Karşılaşılan olay: %d",
		"end.regions": "Kaybedilen bölge: %d",
		"end.rival": "Açığa çıkarılan rakip ağ: %d%%",
		"end.posture": "Duruş: %s",
		"end.new_campaign": "YENİ SEFER",
		"end.try_again": "TEKRAR DENE",
		"tutorial.region": "Hoş geldin Direktör. Dosyasını açmak için haritadaki herhangi bir bölgeye dokun.",
		"tutorial.region_read": "Bu bölge dosyası. İstikrar, Rakip Etkisi ve Gözetim burada çalışmanın riskini belirler. AJAN SEÇ'e dokun.",
		"tutorial.roster": "Her operasyon bir ajan ister. Bu senin kadron.",
		"tutorial.agent": "Ajanlar farklı işlerde güçlüdür. Devam etmek için bir ajan seç.",
		"tutorial.map_signals": "Operasyonlar onaydan önce maliyet, şans ve Isı gösterir. Bölgeyi öğrenmenin en güvenli yolu olan MAP SIGNALS'i seç.",
		"tutorial.resolve": "Operasyonu yürüt ve raporu oku.",
		"tutorial.intel": "İSTİHBARAT analitik kaynağındır. Deep Analysis ve öngörüler için harcanır. Sinyalleri haritalayarak kazanırsın. (Devam etmek için dokun)",
		"tutorial.heat": "ISI ne kadar görünür olduğundur. Yüksek Isı, Küresel İz'i besler ve düşmanca olayları çağırır. Tehlikeye dönüşmeden azalt. (Devam etmek için dokun)",
		"tutorial.rival": "RAKİP AĞ MARUZİYETİ zafer göstergendir. Yerel ağlar kur, sonra Trace Rival Cell ile 100'e taşı. (Devam etmek için dokun)",
		"tutorial.finish": "Gerisi muhakeme. Haritayı izle, dikkatli harca ve dünya dağılmadan ağı açığa çıkar. İyi şanslar Direktör. (Bitirmek için dokun)",
		"how.title": "NASIL OYNANIR",
		"how.mission.title": "Misyon",
		"how.mission.body": "Küresel İz 100 olmadan Rakip Ağ'ı açığa çıkar.",
		"how.mission.losses": "Küresel İz 100'e ulaşırsa, Kurum Güveni 0 olursa veya çok fazla bölge çökerse kaybedersin.",
		"how.flow.title": "Tur Akışı",
		"how.flow.1": "Bölge seç",
		"how.flow.2": "Ajan seç",
		"how.flow.3": "Operasyon seç",
		"how.flow.4": "Sonucu incele",
		"how.flow.5": "Olaylara yanıt ver",
		"how.flow.6": "Tekrarla",
		"how.resources.title": "Kaynaklar",
		"how.res.intel": "Analiz ve bazı operasyonlar için kullanılır. Sinyal haritalayarak kazanılır.",
		"how.res.funds": "Operasyon maliyetleri ve ajan giderlerini karşılar.",
		"how.res.trust": "Yetki zeminin. Güven 0 olursa sefer biter.",
		"how.res.cover": "Operasyonlar ters gittiğinde etkiyi azaltır.",
		"how.res.heat": "Görünürlüğün. Yüksek Isı, Küresel İz'i hızlandırır.",
		"how.global.title": "Küresel Durum",
		"how.global.rival": "Zafer göstergesi. Rakip Ağ Maruziyetini 100'e taşı.",
		"how.global.exposure": "Kayıp göstergesi. Küresel İz 100 olursa kriz kazanır.",
		"how.global.stability_label": "İSTİKRAR",
		"how.global.momentum_label": "İVME",
		"how.global.stability": "Ortalama bölge istikrarı. Düşük istikrar çökme riski demektir.",
		"how.global.momentum": "Rakip ağın baskıyı ne kadar hızlı yaydığını gösterir.",
		"how.first.title": "İlk Hamleler",
		"how.first.1": "Bir bölgeye dokun ve dosyasını oku.",
		"how.first.2": "Operasyona uygun becerilere sahip ajan ata.",
		"how.first.3": "Erken oyunda Sinyalleri Haritala veya Yerel Ağ Kur.",
		"how.first.4": "Şans uygunken Rakip Hücreyi İzle operasyonunu kullan.",
		"how.tips.title": "Operasyon İpuçları",
		"how.tip.1": "Yüksek Isı tehlikeyi artırır.",
		"how.tip.2": "İstikrarlı bölgeleri yönetmek daha kolaydır.",
		"how.tip.3": "Yerel ağlar sonraki operasyonları güçlendirir.",
		"how.tip.4": "Yükselen küresel baskıyı görmezden gelme.",
		"how.intelligence.title": "Bölge İstihbaratı",
		"how.intelligence.map": "Sinyalleri Haritala istihbarat kapsamını yükseltir ve bölge göstergelerini açar.",
		"how.intelligence.analysis": "Derin Analiz bölgenin gizli kimliğini açığa çıkarır.",
		"how.intelligence.identity": "Açığa çıkan kimlik yalnızca desteklediği operasyonları değiştirir.",
		"difficulty.0.short": "Acemi",
		"difficulty.1.short": "Standart",
		"difficulty.2.short": "Kara Oda",
		"game.funds_short": "F",
		"game.intel_short": "İ",
		"game.trust_short": "G",
		"game.difficulty": "DURUŞ",
		"game.lost": "KAYIP",
		"game.world_stability": "İSTİKRAR",
		"game.rival_momentum": "İVME",
		"game.outlook": "ÖNGÖRÜ",
		"game.legend": "LEJANT",
		"hud.risks_nominal": "Kayıp riskleri: Küresel İz 100 / Güven 0 / %d çökmüş bölge.",
		"hud.warning.global": "Kritik: Küresel İz %d/100 seviyesinde.",
		"hud.warning.trust": "Kritik: Kurum Güveni %d seviyesine düştü.",
		"hud.warning.funds": "Kritik: Fon bakiyesi %d ile açıkta.",
		"hud.warning.heat": "Uyarı: Isı %d seviyesine yükseldi.",
		"hud.warning.heat_danger": "Kritik: Isı %d seviyesinde ve Küresel İz'i besliyor.",
		"hud.warning.collapsed": "Kritik: %d/%d bölge çöktü.",
		"hud.warning.momentum": "Uyarı: Rakip İvmesi %d seviyesine ulaştı.",
		"outlook.title": "TUR ÖNGÖRÜSÜ",
		"outlook.economy": "Beklenen Ekonomi",
		"outlook.base_income": "Temel gelir",
		"outlook.trust_income": "Güven katkısı",
		"outlook.agent_upkeep": "Ajan giderleri",
		"outlook.trade_hubs": "Açığa çıkan Ticaret Merkezleri",
		"outlook.budget_change": "Beklenen bütçe değişimi",
		"outlook.pressure": "Pasif Baskı",
		"outlook.heat_change": "Pasif Isı değişimi",
		"outlook.exposure_pressure": "Küresel İz baskısı",
		"outlook.approx": "yaklaşık +%.1f",
		"outlook.rival_activity": "Rakip faaliyeti",
		"outlook.activity.low": "Düşük",
		"outlook.activity.moderate": "Orta",
		"outlook.activity.high": "Yüksek",
		"outlook.disclaimer": "Yalnızca beklenen pasif etkiler gösterilir. Rastgele olaylar ve rakip hedefleri tahmin edilmez.",
		"legend.title": "HARİTA LEJANTI",
		"legend.risk.title": "Risk halkası",
		"legend.risk.body": "Kehribar ve kırmızı çerçeveler bilinen istikrarsızlığı veya rakip baskısını; uyarı işareti ise aciliyeti gösterir.",
		"legend.opportunity.title": "Fırsat halesi",
		"legend.opportunity.body": "Yumuşak yeşil hale, Fırsat göstergesi öğrenildikten sonra güçlü bölgeleri belirtir.",
		"legend.intel.title": "İstihbarat noktaları",
		"legend.intel.body": "Düğümün altındaki üç nokta mevcut istihbarat kapsamını gösterir.",
		"legend.selected.title": "Seçili bölge",
		"legend.selected.body": "Camgöbeği dış halka, incelenen bölge dosyasını belirtir.",
		"legend.collapsed.title": "Çökmüş bölge",
		"legend.collapsed.body": "Soluk ve kırık düğümlerde artık operasyon yürütülemez.",
		"legend.identity.title": "Bilinen kimlik",
		"legend.identity.body": "Küçük baklava işareti yalnızca bölgesel kimlik açığa çıktıktan sonra görünür.",
		"map.lost_short": "KAYIP",
		"assessment.critical": "Kritik",
		"assessment.unstable": "İstikrarsız",
		"assessment.contested": "Çekişmeli",
		"assessment.promising": "Umut verici",
		"assessment.under_observed": "Yetersiz gözlem",
		"assessment.stable": "İstikrarlı",
		"region.classified": "GİZLİ",
		"region.intel_short": "İstihbarat %d/3",
		"region.requires_intel": "İstihbarat Seviyesi %d gerekli",
		"region.plan_operation": "OPERASYON PLANLA",
		"region.section.situation": "Anlık Durum",
		"region.section.metrics": "Bilinen Bölge Göstergeleri",
		"region.section.gaps": "İstihbarat Açıkları",
		"region.section.identity": "Etkin Bölgesel Kimlik",
		"region.section.recommendations": "Stratejik Seçenekler",
		"region.gap.level1": "Sinyalleri Haritala, Rakip Etkisini ve Gözetimi açığa çıkarır.",
		"region.gap.level2": "Sinyalleri Haritala, Kamu Baskısını ve Fırsatı açığa çıkarır.",
		"region.gap.level3": "Bir istihbarat taraması daha bölgesel kapsamı tamamlar.",
		"region.gap.identity": "Derin Analiz, bölgesel kimliği ve operasyon değiştiricilerini açığa çıkarır.",
		"region.summary.unavailable": "Güvenilir bir durum raporu bulunmuyor.",
		"region.summary.collapsed": "Bölge çöktü ve artık operasyonları desteklemiyor.",
		"region.summary.low_stability_limited": "İstikrar bozulurken istihbarat kapsamı sınırlı kalıyor.",
		"region.summary.limited": "Bölge yönetilebilir görünüyor ancak istihbarat kapsamı sınırlı.",
		"region.summary.rival_deteriorating": "Rakip faaliyeti yüksek ve bölgesel istikrar bozuluyor.",
		"region.summary.surveillance": "Bölge ayakta, ancak Gözetim gizli çalışmaları zorlaştırıyor.",
		"region.summary.pressure": "Kamu Baskısı yükseliyor ve bölgesel istikrarı zayıflatabilir.",
		"region.summary.opportunity": "Yerel Fırsat, odaklı operasyonları destekleyecek kadar güçlü.",
		"region.summary.stable": "Bilinen göstergeler istikrarlı; acil bir bölgesel kriz görünmüyor.",
		"advisor.none": "Acil öneri yok. Karar vermeden önce tüm operasyonları incele.",
		"advisor.map_signals": "Eksik bölgesel verilere güvenmeden önce istihbarat kapsamını artır.",
		"advisor.stabilize": "Bölge çöküşe yaklaşmadan önce İstikrarı geri kazan.",
		"advisor.reduce_heat": "Yeni ve görünür bir operasyon Küresel İz'i büyütmeden önce Isıyı düşür.",
		"advisor.counter_influence": "Rakip tutunması açıkça görülürken etkisini kır.",
		"advisor.deep_analysis": "Stratejik avantajını açmak için bölgesel kimliği ortaya çıkar.",
		"advisor.build_network": "Bu bölgedeki gelecek şansları artırmak için Yerel Ağ kur.",
		"advisor.trace_cell": "Ağ desteği, rakip hücreyi izlemeyi değerlendirecek kadar güçlü.",
		"advisor.identity.trade_hub": "Açığa çıkan kimlik genel bütçeyi desteklerken bölgeyi bilinçli kullan.",
		"advisor.identity.media_core": "Medya Çekirdeği avantajından yararlanmak için Isıyı burada düşür.",
		"advisor.identity.border_zone": "Sınır Bölgesi etkiyi büyütürken Rakip Etkisini Kır veya krizi kontrol altına al.",
		"advisor.identity.research_node": "Daha güçlü istihbarat getirisi için Sinyalleri burada Haritala.",
		"advisor.identity.financial_gate": "Fon maliyetleri düşmüşken pahalı operasyonları burada değerlendir.",
		"advisor.identity.civil_pressure_zone": "Sivil Baskı avantajından tam yararlanmak için bölgeyi istikrara kavuştur.",
		"advisor.identity.signal_corridor": "Ağ desteği ve şans uygunken Rakip Hücreyi burada İzle.",
		"advisor.identity.old_alliance": "Sessiz Denetim, bu kimliği ek Güvene dönüştürebilir.",
		"advisor.identity.black_market_route": "Ek Isı kabul edilebilirse Yerel Ağı burada kur.",
		"advisor.identity.diplomatic_junction": "Diplomasi operasyonları en net avantajı burada kazanır.",
		"region_tag.trade_hub.name": "Ticaret Merkezi",
		"region_tag.trade_hub.description": "Açığa çıkan ve etkin her Ticaret Merkezi tur gelirine +2 Fon ekler; toplam katkı +6 ile sınırlıdır.",
		"region_tag.media_core.name": "Medya Çekirdeği",
		"region_tag.media_core.description": "Isıyı Düşür bu bölgede %25 daha fazla Isı kaldırır.",
		"region_tag.border_zone.name": "Sınır Bölgesi",
		"region_tag.border_zone.description": "Rakip Etkisini Kır ve Acil Müdahale etkileri burada %15 daha güçlüdür.",
		"region_tag.research_node.name": "Araştırma Düğümü",
		"region_tag.research_node.description": "Sinyalleri Haritala %25 daha fazla İstihbarat kazandırır; Derin Analiz 2 daha az İstihbarat harcar.",
		"region_tag.financial_gate.name": "Finans Kapısı",
		"region_tag.financial_gate.description": "Bu bölgedeki operasyonların Fon maliyeti %15 azalır.",
		"region_tag.civil_pressure_zone.name": "Sivil Baskı Bölgesi",
		"region_tag.civil_pressure_zone.description": "İstikrara Kavuştur %20 daha fazla İstikrar sağlar ve Kamu Baskısını %15 daha güçlü azaltır.",
		"region_tag.signal_corridor.name": "Sinyal Koridoru",
		"region_tag.signal_corridor.description": "Rakip Hücreyi İzle +8, Sinyalleri Haritala +4 başarı şansı kazanır.",
		"region_tag.old_alliance.name": "Eski İttifak",
		"region_tag.old_alliance.description": "Sessiz Denetim %25 daha fazla Güven sağlar; İstikrara Kavuştur +4 başarı şansı kazanır.",
		"region_tag.black_market_route.name": "Karaborsa Rotası",
		"region_tag.black_market_route.description": "Yerel Ağ Kur %25 daha güçlüdür ancak +2 ek Isı üretir.",
		"region_tag.diplomatic_junction.name": "Diplomatik Kavşak",
		"region_tag.diplomatic_junction.description": "Diplomasi operasyonları +6 başarı şansı kazanır; Sessiz Denetim 2 daha az Fona mal olur.",
		"region_tag.modifier.trade_hub.income": "Açığa çıkan Ticaret Merkezleri bütçe döngüsüne +%d Fon ekledi.",
		"region_tag.modifier.media_core.reduce_heat": "Medya Çekirdeği Isı azaltımını %25 güçlendirir.",
		"region_tag.modifier.border_zone.operation": "Sınır Bölgesi bu operasyonun etkisini %15 güçlendirir.",
		"region_tag.modifier.research_node.map": "Araştırma Düğümü kazanılan İstihbaratı %25 artırır.",
		"region_tag.modifier.research_node.analysis": "Araştırma Düğümü Derin Analiz maliyetini 2 İstihbarat azaltır.",
		"region_tag.modifier.financial_gate.operation": "Finans Kapısı Fon maliyetini %15 azaltır.",
		"region_tag.modifier.civil_pressure.stabilize": "Sivil Baskı Bölgesi hem İstikrarı hem baskı azaltımını güçlendirir.",
		"region_tag.modifier.signal_corridor.trace": "Sinyal Koridoru Rakip Hücreyi İzle şansına +8 ekler.",
		"region_tag.modifier.signal_corridor.map": "Sinyal Koridoru Sinyalleri Haritala şansına +4 ekler.",
		"region_tag.modifier.old_alliance.audit": "Eski İttifak geri kazanılan Güveni %25 artırır.",
		"region_tag.modifier.old_alliance.stabilize": "Eski İttifak İstikrara Kavuştur şansına +4 ekler.",
		"region_tag.modifier.black_market.network": "Karaborsa Rotası ağ büyümesini %25 güçlendirir.",
		"region_tag.modifier.black_market.heat": "Karaborsa Rotası bu operasyona +2 Isı ekler.",
		"region_tag.modifier.diplomatic.operation": "Diplomatik Kavşak diplomasi işlerine +6 şans ekler ve Sessiz Denetimi ucuzlatır.",
		"region_tag.discovery_reward": "İlk kimlik keşfi +%d İstihbarat kazandırdı.",
		"skill.analysis": "Analiz",
		"skill.fieldcraft": "Saha Becerisi",
		"skill.diplomacy": "Diplomasi",
		"skill.technical": "Teknik",
		"skill.resolve": "Soğukkanlılık",
		"skill.analysis.short": "ANL",
		"skill.fieldcraft.short": "SAH",
		"skill.diplomacy.short": "DİP",
		"skill.technical.short": "TEK",
		"skill.resolve.short": "SĞK",
		"agent_role.analyst": "Analist",
		"agent_role.field_observer": "Saha Gözlemcisi",
		"agent_role.liaison": "İrtibat Sorumlusu",
		"agent_role.signal_specialist": "Sinyal Uzmanı",
		"agent_role.crisis_negotiator": "Kriz Müzakerecisi",
		"agent_role.network_handler": "Ağ Yöneticisi",
		"agent.strengths": "Güçlü yönler: %s",
		"agent.fit.strong": "Güçlü uyum",
		"agent.fit.viable": "Uygun",
		"agent.fit.risky": "Riskli",
		"agent.fit.exhausted": "Tükenmiş",
		"agent.fit.specialist": "Uzman avantajı",
		"agent.fit.tradeoff": "Özellik ödünleşimi",
		"agent.fit.best": "Mevcut en iyi seçenek: %s, %d%%",
		"agent_trait.fast_analyst.name": "Hızlı Analist",
		"agent_trait.fast_analyst.description": "Sinyalleri Haritala daha fazla İstihbarat üretir.",
		"agent_trait.low_profile.name": "Düşük Profil",
		"agent_trait.low_profile.description": "Operasyonlar daha az Isı üretir.",
		"agent_trait.risk_averse.name": "Riskten Kaçınan",
		"agent_trait.risk_averse.description": "Daha güvenli şanslar, ancak daha zayıf başarılı etkiler.",
		"agent_trait.expensive_specialist.name": "Pahalı Uzman",
		"agent_trait.expensive_specialist.description": "Daha yüksek Fon maliyeti karşılığında daha iyi şans.",
		"agent_trait.calm_under_pressure.name": "Baskı Altında Sakin",
		"agent_trait.calm_under_pressure.description": "Başarısızlık cezaları azalır.",
		"agent_trait.unstable_contact.name": "Dengesiz Bağlantı",
		"agent_trait.unstable_contact.description": "Daha güçlü etkiler, daha yüksek olay riski.",
		"agent_trait.modifier.expensive.chance": "Pahalı Uzman başarı şansını artırır.",
		"agent_trait.modifier.expensive.cost": "Pahalı Uzman Fon maliyetini artırır.",
		"agent_trait.modifier.risk_averse.chance": "Riskten Kaçınan başarı şansını artırır.",
		"agent_trait.modifier.risk_averse.effect": "Riskten Kaçınan başarılı etkilerin gücünü azaltır.",
		"agent_trait.modifier.low_profile.heat": "Düşük Profil üretilen Isıyı azaltır.",
		"agent_trait.modifier.fast_analyst.intel": "Hızlı Analist, Sinyalleri Haritala ile kazanılan İstihbaratı artırır.",
		"agent_trait.modifier.calm.failure": "Baskı Altında Sakin başarısızlık sonuçlarını azaltır.",
		"agent_trait.modifier.unstable.effect": "Dengesiz Bağlantı başarılı etkileri güçlendirir.",
		"agent_trait.modifier.unstable.event": "Dengesiz Bağlantı bu turun olay riskini artırdı.",
		"operation.map_signals.name": "Sinyalleri Haritala",
		"operation.map_signals.description": "İstihbarat Seviyesini yükseltmek ve İstihbarat kazanmak için açık kanalları tara.",
		"operation.map_signals.effect": "+1 İstihbarat Seviyesi ve +İstihbarat",
		"operation.build_network.name": "Yerel Ağ Kur",
		"operation.build_network.description": "Bu bölgedeki gelecek çalışmaları desteklemek için sessiz bağlantılar kur.",
		"operation.build_network.effect": "+Yerel Ağ",
		"operation.counter_influence.name": "Rakip Etkisini Kır",
		"operation.counter_influence.description": "Görünür bir iz bırakmayı göze alarak rakip tutunmasını boz.",
		"operation.counter_influence.effect": "-Rakip Etkisi",
		"operation.stabilize.name": "Bölgeyi İstikrara Kavuştur",
		"operation.stabilize.description": "İstikrarı geri kazanmak ve baskıyı azaltmak için yerel kurumları koordine et.",
		"operation.stabilize.effect": "+İstikrar ve -Kamu Baskısı",
		"operation.reduce_heat.name": "Isıyı Düşür",
		"operation.reduce_heat.description": "Operasyon izlerini temizle ve Direktörlük Örtüsünü yenile.",
		"operation.reduce_heat.effect": "-Isı ve +Örtü",
		"operation.trace_cell.name": "Rakip Hücreyi İzle",
		"operation.trace_cell.description": "Rakip bağlantıları kaynağına kadar takip et. Zaferin ana yolu budur.",
		"operation.trace_cell.effect": "+Rakip Ağ Maruziyeti",
		"operation.containment.name": "Acil Müdahale",
		"operation.containment.description": "Çökmekte olan bir bölgeyi hızla tutmak için yüksek kaynak ayır.",
		"operation.containment.effect": "Yüksek +İstikrar ve -Rakip Etkisi",
		"operation.deep_analysis.name": "Derin Analiz",
		"operation.deep_analysis.description": "Bölgesel kimliği açığa çıkarmak ve kapsamı tamamlamak için dosyayı çapraz incele.",
		"operation.deep_analysis.effect": "Kimliği açığa çıkar ve İstihbarat Seviyesini en yükseğe getir",
		"operation.quiet_audit.name": "Sessiz Denetim",
		"operation.quiet_audit.description": "Kurum içi güveni geri kazan ve Kamu Baskısını yatıştır.",
		"operation.quiet_audit.effect": "+Güven ve -Kamu Baskısı",
		"operation.context.region": "%s / %s",
		"operation.context.agent": "%s / Yorgunluk %d",
		"operation.required_skill": "Gerekli beceri",
		"operation.skill_value": "%s %d",
		"operation.chance_label": "ŞANS",
		"operation.modifier.identity": "Kimlik",
		"operation.modifier.agent": "Ajan özelliği",
		"operation.risk.favorable": "Elverişli",
		"operation.risk.uncertain": "Belirsiz",
		"operation.risk.risky": "Riskli",
		"operation.risk.severe": "Ağır risk",
		"operation.warning.resources": "Yetersiz Fon veya İstihbarat onayı engelliyor.",
		"operation.warning.fatigue": "Yüksek Yorgunluk, ajanın gerçek başarı şansını düşürüyor.",
		"operation.warning.low_network": "Düşük Yerel Ağ, hücreyi izlemenin değerini ve şansını sınırlar.",
		"operation.warning.surveillance": "Bilinen Gözetim bu gizli operasyonu zorlaştırıyor.",
		"operation.warning.low_trust": "Mevcut yetki düzeyinde Güven maliyeti tehlikeli.",
		"operation.warning.high_heat": "Mevcut Isı uzun vadeli Küresel İz baskısını zaten artırıyor.",
		"operation.confirm.low_chance": "Nihai başarı şansı olağandışı derecede düşük.",
		"operation.confirm.high_heat": "Bu hamle Isıyı kritik aralığa taşıyacak.",
		"operation.confirm.low_trust": "Bu hamle Güveni çöküş sınırına yaklaştıracak.",
		"operation.confirm.negative_funds": "Bu hamle kullanılabilir Fonları aşacak.",
		"operation.confirm_risk": "RİSKİ ONAYLA",
		"operation.unavailable": "Kullanılamıyor: mevcut kaynak veya bölge kuralları onayı engelliyor.",
		"operation.unavailable_short": "KULLANILAMIYOR",
		"operation.breakdown.title": "Hesap Ayrıntıları",
		"operation.breakdown.chance": "Başarı Şansı",
		"operation.breakdown.funds": "Fon Maliyeti",
		"operation.breakdown.intel": "İstihbarat Maliyeti",
		"operation.breakdown.trust": "Güven Maliyeti",
		"operation.breakdown.heat": "Üretilen Isı",
		"breakdown.base": "Temel",
		"breakdown.agent_skill": "Ajan becerisi",
		"breakdown.fatigue": "Yorgunluk",
		"breakdown.local_network": "Yerel Ağ",
		"breakdown.intel_level": "İstihbarat Seviyesi",
		"breakdown.surveillance": "Gözetim",
		"breakdown.rival_influence": "Rakip Etkisi",
		"breakdown.difficulty": "Duruş",
		"breakdown.agent_trait": "Ajan özelliği",
		"breakdown.region_identity": "Bölgesel kimlik",
		"breakdown.final": "Nihai",
		"debrief.operation_context": "%s / %s / %s",
		"debrief.chance_roll": "Nihai şans %d%% / Zar %d",
		"debrief.section.effects": "Anlık Etkiler",
		"debrief.section.modifiers": "Uygulanan Değiştiriciler",
		"debrief.section.identity": "Kimlik Açığa Çıktı",
		"debrief.section.economy": "Tur Ekonomisi",
		"debrief.section.world": "Rakip ve Dünya Tepkisi",
		"debrief.section.changes": "Değişen Sefer Durumu",
		"debrief.identity_delta.chance": "Bölgesel kimlik nihai şansı %s değiştirdi.",
		"debrief.identity_delta.cost": "Bölgesel kimlik %s maliyetini %s değiştirdi.",
		"debrief.identity_delta.heat": "Bölgesel kimlik üretilen Isıyı %s değiştirdi.",
		"debrief.identity_delta.effect": "Bölgesel kimlik %s etkisini %s değiştirdi.",
		"debrief.metric.funds": "Fon",
		"debrief.metric.intel": "İstihbarat",
		"debrief.metric.trust": "Güven",
		"debrief.metric.heat": "Isı",
		"debrief.metric.cover": "Örtü",
		"debrief.metric.rival_exposure": "Rakip Ağ Maruziyeti",
		"debrief.metric.global_exposure": "Küresel İz",
		"debrief.metric.region_stability": "Bölge İstikrarı",
		"debrief.metric.region_rival": "Bölge Rakip Etkisi",
		"debrief.metric.region_pressure": "Bölge Kamu Baskısı",
		"debrief.metric.local_network": "Yerel Ağ",
		"debrief.metric.intel_level": "İstihbarat Seviyesi",
		"debrief.metric.rival_momentum": "Rakip İvmesi",
		"debrief.metric.world_stability": "Dünya İstikrarı",
		"debrief.metric.collapsed_regions": "Çökmüş Bölgeler",
		"debrief.metric.stability": "İstikrar",
		"debrief.metric.rival_influence": "Rakip Etkisi",
		"debrief.metric.public_pressure": "Kamu Baskısı",
		"resolve.trust_spent": "Komite onayı harcandı: -%d Güven.",
		"resolve.heat_gain": "Operasyon izi: +%d Isı.",
		"resolve.near_miss": "Operasyon hedefe ulaşamadı ancak kullanılabilir parçalar kurtarıldı.",
		"resolve.identity_revealed": "%s, %s olarak tanımlandı. İlk keşif ödülü: +%d İstihbarat.",
		"resolve.event_identity_revealed": "%s, %s olarak tanımlandı.",
		"resolve.map_signals": "%s haritalandı: İstihbarat Seviyesi %d, +%d İstihbarat.",
		"resolve.build_network": "%s bölgesindeki Yerel Ağ %d büyüdü; güncel değer %d.",
		"resolve.counter_influence": "%s bölgesindeki Rakip Etkisi %d azaldı.",
		"resolve.stabilize": "%s istikrara kavuştu: +%d İstikrar, -%d Kamu Baskısı.",
		"resolve.reduce_heat": "İzler temizlendi: -%d Isı, +%d Örtü.",
		"resolve.trace_cell": "%s üzerinden hücre izlendi: +%d Rakip Ağ Maruziyeti.",
		"resolve.containment": "%s kontrol altına alındı: +%d İstikrar, -%d Rakip Etkisi.",
		"resolve.deep_analysis": "%s profili tamamlandı. Kimlik: %s.",
		"resolve.quiet_audit": "Denetim tamamlandı: +%d Güven; %s bölgesinde Kamu Baskısı azaldı.",
		"resolve.cover_absorb": "Örtü varlıkları etkinin bir kısmını emdi: -%d Örtü.",
		"resolve.failure": "Başarısızlık sonucu: +%d Isı, -%d Güven, %s İstikrarı -%d.",
		"resolve.surveillance_tightened": "%s bölgesinde yerel Gözetim sıkılaştı.",
		"resolve.level_up": "%s Seviye %d oldu; %s gelişti.",
		"resolve.budget_cycle": "Bütçe döngüsü: +%d gelir, -%d gider.",
		"resolve.trade_hub_income": "Açığa çıkan Ticaret Merkezleri +%d Fon sağladı.",
		"resolve.passive_heat": "Pasif temizlik Isıyı %d azalttı.",
		"resolve.exposure_pressure": "Pasif baskı yaklaşık %.1f Küresel İz ekledi.",
		"resolve.overdrawn": "UYARI: Direktörlük açıkta. Fonları bu tur içinde düzelt.",
		"resolve.rival_spread": "Rakip sinyalleri şu bölgelerde güçlendi: %s.",
		"resolve.region_collapsed": "BÖLGE ÇÖKTÜ: %s düzensizliğe sürüklendi.",
		"tutorial.intel_identity": "Sinyalleri Haritala istihbarat kapsamını yükseltir. Derin Analiz bölgesel kimliği açar; açığa çıkan kimlikler uygun operasyonları değiştirir. (Devam etmek için dokun)",
		"tutorial.heat_network": "Ajan becerisi ve Yorgunluk gerçek şansı değiştirir. Yerel Ağ gelecekteki işleri destekler; Isı ise uzun vadeli tehlikeyi büyütür. (Devam etmek için dokun)",
		"tutorial.identity_revealed": "Kimlik doğrulandı. Her kimlik farklı operasyonları değiştirir; burada yeniden plan yapmadan önce dosyadaki etkiyi oku. (Geri dönmek için dokun)",
	},
}

var _locale: String = DEFAULT_LOCALE


func _ready() -> void:
	_locale = _normalize_locale(SettingsManager.language_code)


func current_locale() -> String:
	return _locale


func language_label(locale: String = "") -> String:
	var code := _locale if locale == "" else locale
	for entry in LANGUAGES:
		if entry["code"] == code:
			return String(entry["label"])
	return "English"


func language_codes() -> Array[String]:
	var out: Array[String] = []
	for entry in LANGUAGES:
		out.append(String(entry["code"]))
	return out


func set_locale(locale: String) -> void:
	var next := _normalize_locale(locale)
	if _locale == next:
		return
	_locale = next
	SettingsManager.language_code = next
	SettingsManager.save_settings()
	locale_changed.emit(_locale)


func t(key: String, args: Array = []) -> String:
	var table: Dictionary = TEXT.get(_locale, TEXT[DEFAULT_LOCALE])
	var fallback: Dictionary = TEXT[DEFAULT_LOCALE]
	var value: String = String(table.get(key, fallback.get(key, key)))
	if args.is_empty():
		return value
	return value % args


func _normalize_locale(locale: String) -> String:
	for entry in LANGUAGES:
		if entry["code"] == locale:
			return locale
	return DEFAULT_LOCALE
