extends Node
## TurnResolver.gd - all operation resolution and turn advancement rules.
## Reads and mutates GameState; produces result dictionaries the UI renders.
## No UI code, no drawing, no scene logic.

const SKILL_NAMES := {
	"analysis": "Analysis", "fieldcraft": "Fieldcraft", "diplomacy": "Diplomacy",
	"technical": "Technical", "resolve": "Resolve",
}


# ---------- Previews (used by OperationPanel before confirming) ----------

func compute_chance(region: Dictionary, agent: Dictionary, op: Dictionary) -> int:
	var skill_key: String = op.get("skill", "analysis")
	var skill := float(agent.get(skill_key, 1))
	var chance := float(op.get("base_chance", 50))
	chance += skill * Balance.W_SKILL
	chance -= float(agent["fatigue"]) * Balance.W_FATIGUE
	chance += float(region["local_network"]) * Balance.W_NETWORK
	chance += float(region["intel_level"]) * Balance.W_INTEL_LEVEL
	if op.get("covert", false):
		chance -= float(region["surveillance"]) * Balance.W_SURVEILLANCE
		chance -= float(region["rival_influence"]) * Balance.W_RIVAL
	chance += float(Balance.CHANCE_MOD[GameState.difficulty])
	match agent.get("trait", ""):
		"expensive_specialist":
			chance += Balance.TRAIT_EXPENSIVE_CHANCE
		"risk_averse":
			chance += Balance.TRAIT_RISK_AVERSE_CHANCE
	return clampi(int(round(chance)), Balance.CHANCE_MIN, Balance.CHANCE_MAX)


func compute_costs(agent: Dictionary, op: Dictionary) -> Dictionary:
	var funds_cost := int(op.get("cost_funds", 0))
	if agent.get("trait", "") == "expensive_specialist":
		funds_cost = int(round(funds_cost * Balance.TRAIT_EXPENSIVE_COST_MULT))
	return {
		"funds": funds_cost,
		"intel": int(op.get("cost_intel", 0)),
		"trust": int(op.get("extra_cost_trust", 0)),
	}


func can_afford(costs: Dictionary) -> bool:
	return GameState.funds >= int(costs["funds"]) and GameState.intel >= int(costs["intel"])


func heat_preview(agent: Dictionary, op: Dictionary) -> int:
	var h := float(op.get("heat", 0)) * Balance.HEAT_PENALTY_RATE[GameState.difficulty]
	if agent.get("trait", "") == "low_profile":
		h *= Balance.TRAIT_LOW_PROFILE_HEAT_MULT
	return int(round(h))


# ---------- Operation resolution ----------

func resolve_operation(region_id: String, agent_id: String, op_id: String) -> Dictionary:
	var region: Dictionary = GameState.get_region(region_id)
	var agent: Dictionary = GameState.get_agent(agent_id)
	var op: Dictionary = OperationData.get_def(op_id)
	var chance := compute_chance(region, agent, op)
	var costs := compute_costs(agent, op)
	var roll := RandomService.rand_int(1, 100)
	var success := roll <= chance
	var near_miss := not success and roll <= chance + 15
	var lines: Array[String] = []
	var effect_mult := _effect_multiplier(agent)

	# Pay costs up front; failure does not refund them.
	GameState.add_resources({
		"funds": -int(costs["funds"]),
		"intel": -int(costs["intel"]),
		"trust": -int(costs["trust"]),
	})
	if int(costs["trust"]) > 0:
		lines.append("Committee approval spent: -%d Trust" % int(costs["trust"]))

	# Heat is generated by acting at all, success or not.
	var heat_gain := heat_preview(agent, op)
	if heat_gain != 0:
		GameState.add_resources({"heat": heat_gain})
		lines.append("Operational footprint: +%d Heat" % heat_gain)

	if success:
		lines.append_array(_apply_success(region, agent, op, effect_mult))
	elif near_miss:
		lines.append("The operation fell short, but fragments were salvaged.")
		lines.append_array(_apply_success(region, agent, op, effect_mult * Balance.OP_PARTIAL_EFFECT_MULT))
		lines.append_array(_apply_failure(region, agent, op, 0.5))
	else:
		lines.append_array(_apply_failure(region, agent, op, 1.0))

	# Fatigue and experience.
	agent["fatigue"] = clampi(int(agent["fatigue"]) + int(op.get("fatigue", 10)), 0, 100)
	agent["status"] = "Strained" if int(agent["fatigue"]) >= Balance.FATIGUE_STRAINED_THRESHOLD else "Ready"
	_grant_xp(agent, Balance.XP_SUCCESS if success else Balance.XP_FAIL, lines)

	GameState.stats["ops_run"] = int(GameState.stats.get("ops_run", 0)) + 1
	if success:
		GameState.stats["ops_won"] = int(GameState.stats.get("ops_won", 0)) + 1
	GameState.region_updated.emit(region_id)

	return {
		"success": success,
		"near_miss": near_miss,
		"chance": chance,
		"roll": roll,
		"op_name": op.get("name", op_id),
		"op_id": op_id,
		"region_name": region.get("name", region_id),
		"region_id": region_id,
		"agent_name": agent.get("name", agent_id),
		"lines": lines,
	}


func _apply_success(region: Dictionary, agent: Dictionary, op: Dictionary, mult: float) -> Array[String]:
	var lines: Array[String] = []
	match op["id"]:
		"map_signals":
			region["intel_level"] = mini(3, int(region["intel_level"]) + 1)
			var gain := float(Balance.OP_MAP_SIGNALS_INTEL) * mult
			if agent.get("trait", "") == "fast_analyst":
				gain *= Balance.TRAIT_FAST_ANALYST_INTEL_MULT
			GameState.add_resources({"intel": int(round(gain))})
			lines.append("%s charted: Intel Level %d, +%d Intel" % [region["name"], int(region["intel_level"]), int(round(gain))])
		"build_network":
			var n := int(round(Balance.OP_BUILD_NETWORK_GAIN * mult))
			region["local_network"] = clampi(int(region["local_network"]) + n, 0, 100)
			lines.append("Local network in %s grew by %d (now %d)" % [region["name"], n, int(region["local_network"])])
		"counter_influence":
			var cut := int(round(Balance.OP_COUNTER_INFLUENCE_REDUCE * mult))
			region["rival_influence"] = clampi(int(region["rival_influence"]) - cut, 0, 100)
			lines.append("Rival influence in %s reduced by %d" % [region["name"], cut])
		"stabilize":
			var s := int(round(Balance.OP_STABILIZE_GAIN * mult))
			region["stability"] = clampi(int(region["stability"]) + s, 0, 100)
			region["public_pressure"] = clampi(int(region["public_pressure"]) - Balance.OP_STABILIZE_PRESSURE_CUT, 0, 100)
			lines.append("%s stabilized: +%d Stability, pressure eased" % [region["name"], s])
		"reduce_heat":
			var h := int(round(Balance.OP_REDUCE_HEAT_AMOUNT * mult))
			GameState.add_resources({"heat": -h, "cover": Balance.OP_REDUCE_HEAT_COVER})
			lines.append("Trails scrubbed: -%d Heat, +%d Cover" % [h, Balance.OP_REDUCE_HEAT_COVER])
		"trace_cell":
			var exposure := (float(Balance.OP_TRACE_EXPOSURE_BASE) + float(region["local_network"]) * Balance.OP_TRACE_EXPOSURE_NETWORK_BONUS) * mult
			GameState.add_resources({"rival_exposure": int(round(exposure))})
			region["rival_influence"] = clampi(int(region["rival_influence"]) - Balance.OP_TRACE_RIVAL_CUT, 0, 100)
			lines.append("Cell traced through %s: +%d Rival Network Exposure" % [region["name"], int(round(exposure))])
		"containment":
			var st := int(round(Balance.OP_CONTAIN_STABILITY * mult))
			region["stability"] = clampi(int(region["stability"]) + st, 0, 100)
			region["rival_influence"] = clampi(int(region["rival_influence"]) - Balance.OP_CONTAIN_RIVAL_CUT, 0, 100)
			lines.append("%s contained: +%d Stability, rival pushed back" % [region["name"], st])
		"deep_analysis":
			region["tag_revealed"] = true
			region["intel_level"] = 3
			lines.append("%s profile complete. Identified as: %s" % [region["name"], region["hidden_tag"]])
		"quiet_audit":
			var t := int(round(Balance.OP_QUIET_AUDIT_TRUST * mult))
			GameState.add_resources({"trust": t})
			region["public_pressure"] = clampi(int(region["public_pressure"]) - Balance.OP_QUIET_AUDIT_PRESSURE_CUT, 0, 100)
			lines.append("Audit filed: +%d Trust, public pressure in %s eased" % [t, region["name"]])
	return lines


func _apply_failure(region: Dictionary, agent: Dictionary, op: Dictionary, scale: float) -> Array[String]:
	var lines: Array[String] = []
	var rate := Balance.FAIL_PENALTY_RATE[GameState.difficulty] * scale
	if agent.get("trait", "") == "calm_under_pressure":
		rate *= Balance.TRAIT_CALM_FAIL_MULT
	# Cover can absorb part of a failure.
	if GameState.cover >= Balance.OP_FAIL_COVER_ABSORB:
		GameState.add_resources({"cover": -Balance.OP_FAIL_COVER_ABSORB})
		rate *= 0.5
		lines.append("Cover assets absorbed part of the fallout (-%d Cover)" % Balance.OP_FAIL_COVER_ABSORB)
	var heat_hit := int(round(Balance.OP_FAIL_HEAT_BONUS * rate))
	var trust_hit := int(round(Balance.OP_FAIL_TRUST_HIT * rate))
	var stab_hit := int(round(Balance.OP_FAIL_STABILITY_HIT * rate))
	GameState.add_resources({"heat": heat_hit, "trust": -trust_hit})
	region["stability"] = clampi(int(region["stability"]) - stab_hit, 0, 100)
	lines.append("Operation failed: +%d Heat, -%d Trust, %s stability -%d" % [heat_hit, trust_hit, region["name"], stab_hit])
	if op.get("covert", false):
		region["surveillance"] = clampi(int(region["surveillance"]) + 5, 0, 100)
		lines.append("Local surveillance in %s tightened" % region["name"])
	return lines


func _effect_multiplier(agent: Dictionary) -> float:
	match agent.get("trait", ""):
		"risk_averse":
			return Balance.TRAIT_RISK_AVERSE_EFFECT_MULT
		"unstable_contact":
			return Balance.TRAIT_UNSTABLE_EFFECT_MULT
	return 1.0


func _grant_xp(agent: Dictionary, xp: int, lines: Array[String]) -> void:
	agent["xp"] = int(agent["xp"]) + xp
	var needed := int(agent["level"]) * Balance.XP_PER_LEVEL
	if int(agent["xp"]) >= needed and int(agent["level"]) < Balance.LEVEL_MAX:
		agent["xp"] = int(agent["xp"]) - needed
		agent["level"] = int(agent["level"]) + 1
		# Level up sharpens the agent's strongest skill.
		var best_key := "analysis"
		for key in ["analysis", "fieldcraft", "diplomacy", "technical", "resolve"]:
			if int(agent[key]) > int(agent[best_key]):
				best_key = key
		agent[best_key] = mini(Balance.SKILL_MAX, int(agent[best_key]) + 1)
		lines.append("%s reached level %d (%s improved)" % [agent["name"], int(agent["level"]), SKILL_NAMES[best_key]])


# ---------- Turn advancement ----------

## Runs world upkeep after the player's operation cycle (or a passed turn).
## Returns {lines, event, end}.
func advance_turn(acted_agent_id: String = "") -> Dictionary:
	var lines: Array[String] = []
	var extra_event_chance := 0.0
	if acted_agent_id != "":
		var acted: Dictionary = GameState.get_agent(acted_agent_id)
		if acted.get("trait", "") == "unstable_contact":
			extra_event_chance = Balance.TRAIT_UNSTABLE_EVENT_BONUS

	# Income and upkeep.
	var income := Balance.BASE_INCOME + GameState.trust / Balance.INCOME_TRUST_DIVISOR
	var upkeep := GameState.agents.size() * Balance.AGENT_UPKEEP
	GameState.add_resources({"funds": income - upkeep})
	lines.append("Budget cycle: +%d income, -%d upkeep" % [income, upkeep])

	# Passive heat decay.
	if GameState.heat > 0:
		GameState.add_resources({"heat": -Balance.HEAT_DECAY_PER_TURN})

	# Resting agents recover.
	for a in GameState.agents:
		if a["id"] != acted_agent_id and int(a["fatigue"]) > 0:
			a["fatigue"] = maxi(0, int(a["fatigue"]) - Balance.FATIGUE_RECOVERY_PER_TURN)
			a["status"] = "Strained" if int(a["fatigue"]) >= Balance.FATIGUE_STRAINED_THRESHOLD else "Ready"

	# Rival network grows and spreads.
	GameState.rival_momentum = clampf(
		GameState.rival_momentum + Balance.RIVAL_MOMENTUM_GROWTH * Balance.RIVAL_SPREAD_RATE[GameState.difficulty],
		0.0, float(Balance.RIVAL_MOMENTUM_MAX))
	lines.append_array(_spread_rival())

	# Rival-held regions erode; collapses cascade pressure to neighbors.
	lines.append_array(_erode_and_collapse())

	# Global exposure creep from heat and rival momentum.
	var exposure_gain := (GameState.heat / Balance.HEAT_TO_EXPOSURE + GameState.rival_momentum / Balance.MOMENTUM_TO_EXPOSURE) \
		* Balance.EXPOSURE_RATE[GameState.difficulty]
	GameState.add_resources({"global_exposure": exposure_gain})

	if GameState.funds < 0:
		lines.append("WARNING: The Directorate is overdrawn. Restore Funds now or be dissolved.")

	GameState.turn += 1
	var end := GameState.check_end_conditions()
	var event: Dictionary = {}
	if not end["over"]:
		event = EventData.pick_event(GameState, extra_event_chance)
	return {"lines": lines, "event": event, "end": end}


func _spread_rival() -> Array[String]:
	var lines: Array[String] = []
	var live: Array = GameState.active_regions()
	if live.is_empty():
		return lines
	# Prefer spreading from strongholds into their neighbors.
	var sources := live.filter(func(r): return int(r["rival_influence"]) >= 50)
	var targets: Array = []
	for src in sources:
		for nid in RegionData.neighbors_of(src["id"]):
			var n: Dictionary = GameState.get_region(nid)
			if not n.is_empty() and not n["collapsed"]:
				targets.append(n)
	if targets.is_empty():
		targets = live
	targets = RandomService.shuffled(targets).slice(0, Balance.RIVAL_SPREAD_TARGETS)
	var amount := int(round(Balance.RIVAL_SPREAD_BASE * (0.5 + GameState.rival_momentum / 100.0) \
		* Balance.RIVAL_SPREAD_RATE[GameState.difficulty]))
	for t in targets:
		t["rival_influence"] = clampi(int(t["rival_influence"]) + amount, 0, 100)
		GameState.region_updated.emit(t["id"])
	if amount > 0 and not targets.is_empty():
		var names := ", ".join(targets.map(func(t): return String(t["name"])))
		lines.append("Rival signals strengthen in: %s" % names)
	return lines


func _erode_and_collapse() -> Array[String]:
	var lines: Array[String] = []
	for r in GameState.active_regions():
		if int(r["rival_influence"]) >= Balance.RIVAL_STABILITY_EROSION_THRESHOLD:
			r["stability"] = clampi(int(r["stability"]) - Balance.RIVAL_STABILITY_EROSION, 0, 100)
			r["public_pressure"] = clampi(int(r["public_pressure"]) + Balance.RIVAL_PRESSURE_GAIN, 0, 100)
		if int(r["stability"]) < Balance.COLLAPSE_STABILITY_THRESHOLD:
			GameState.collapse_region(r)
			GameState.add_resources({"global_exposure": Balance.COLLAPSE_EXPOSURE_SPIKE})
			lines.append("REGION COLLAPSED: %s has fallen into disorder." % r["name"])
			for nid in RegionData.neighbors_of(r["id"]):
				var n: Dictionary = GameState.get_region(nid)
				if not n.is_empty() and not n["collapsed"]:
					n["stability"] = clampi(int(n["stability"]) - Balance.COLLAPSE_NEIGHBOR_STABILITY_HIT, 0, 100)
					GameState.region_updated.emit(nid)
	return lines
